antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validator_rejects_hole_body	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAbdmFsaWRhdG9yX3JlamVjdHNfaG9sZV9ib2R5	key=a2VybmVsL3Byb2JlfCMw	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_def_builtin_op	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAUY2hlY2tfZGVmX2J1aWx0aW5fb3A=	key=a2VybmVsL3Byb2JlfCMx	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: remap_index_passthrough	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXcmVtYXBfaW5kZXhfcGFzc3Rocm91Z2g=	key=a2VybmVsL3Byb2JlfCMy	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_under_application	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWY2VydF91bmRlcl9hcHBsaWNhdGlvbg==	key=a2VybmVsL3Byb2JlfCMz	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: positivity_through_ctor	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXcG9zaXRpdml0eV90aHJvdWdoX2N0b3I=	key=a2VybmVsL3Byb2JlfCM0	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: quote_foreign_vdata	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATcXVvdGVfZm9yZWlnbl92ZGF0YQ==	key=a2VybmVsL3Byb2JlfCM1	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: decode_unknown_symbol	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAVZGVjb2RlX3Vua25vd25fc3ltYm9s	key=a2VybmVsL3Byb2JlfCM2	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validate_cert_builtin_op	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYdmFsaWRhdGVfY2VydF9idWlsdGluX29w	key=a2VybmVsL3Byb2JlfCM3	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_def_unknown	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARY2hlY2tfZGVmX3Vua25vd24=	key=a2VybmVsL3Byb2JlfCM4	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_ctor_arity	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAQY2hlY2tfY3Rvcl9hcml0eQ==	key=a2VybmVsL3Byb2JlfCM5	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_dangling_callee	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAUY2VydF9kYW5nbGluZ19jYWxsZWU=	key=a2VybmVsL3Byb2JlfCMxMA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_nondata_scrutinee	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWZXZhbF9ub25kYXRhX3NjcnV0aW5lZQ==	key=a2VybmVsL3Byb2JlfCMxMQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: conv_unknown_ctor_fallback	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaY29udl91bmtub3duX2N0b3JfZmFsbGJhY2s=	key=a2VybmVsL3Byb2JlfCMxMg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: apply_nonfun	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAMYXBwbHlfbm9uZnVu	key=a2VybmVsL3Byb2JlfCMxMw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_absurd	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAMaW5mZXJfYWJzdXJk	key=a2VybmVsL3Byb2JlfCMxNA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validator_warn_emit	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATdmFsaWRhdG9yX3dhcm5fZW1pdA==	key=a2VybmVsL3Byb2JlfCMxNQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: normalize_opts	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAObm9ybWFsaXplX29wdHM=	key=a2VybmVsL3Byb2JlfCMxNg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_fields_only_ctor	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWaW5mZXJfZmllbGRzX29ubHlfY3Rvcg==	key=a2VybmVsL3Byb2JlfCMxNw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_no_branch	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAOZXZhbF9ub19icmFuY2g=	key=a2VybmVsL3Byb2JlfCMxOA==	pieces=
antigen-record	kind=family	assay=positivity	label=positive	seed=-	note=occurs?/2 coverage (packed): 6 arrow-domain shapes	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAACdAAAAAVtAAAACWFyZ19uYW1lc2wAAAADbQAAAANwcTBtAAAAA3BxMW0AAAADcHEyam0AAAAEbmFtZW0AAAADUEMwbQAAAApxdWFudGl0aWVzbAAAAANtAAAAB3ByZXNlbnRtAAAAB3ByZXNlbnRtAAAAB3ByZXNlbnRqbQAAAApyaWR4X2NvdW50YQBtAAAADHJwYXJhbV9jb3VudGEAdAAAAAVtAAAACWFyZ19uYW1lc2wAAAADbQAAAANwcTBtAAAAA3BxMW0AAAADcHEyam0AAAAEbmFtZW0AAAADUEMxbQAAAApxdWFudGl0aWVzbAAAAANtAAAAB3ByZXNlbnRtAAAAB3ByZXNlbnRtAAAAB3ByZXNlbnRqbQAAAApyaWR4X2NvdW50YQBtAAAADHJwYXJhbV9jb3VudGEAam0AAAAPZmFtX2luZGV4X25hbWVzam0AAAAJZmFtX2xldmVsYQBtAAAACGZhbV9uYW1lbQAAAARQZ2VubQAAAA9mYW1fcGFyYW1fbmFtZXNq	key=cG9zaXRpdml0eXxjdG9yOjA6YXJnOjAocGkgKGN0b3IgUyAoY3RvciBaKSkgKGRhdGEgTmF0ICgpICgpKSl8Y3RvcjowOmFyZzoxKHBpIChkYXRhIEVxdWl2YWxlbnQgKChkYXRhIE5hdCAoKSAoKSkpICgoY3RvciBaKSAoY3RvciBaKSkpIChpbnQtdHlwZSkpfGN0b3I6MDphcmc6MihwaSAoY3RvciByZWZsZXhpdmUgKGN0b3IgWikpIChkYXRhIE5hdCAoKSAoKSkpfGN0b3I6MTphcmc6MChwaSAoY2FzZSAoY3RvciByZWZsZXhpdmUgKGN0b3IgWikpIChjdG9yIFopIChicmFuY2ggcmVmbGV4aXZlIDEgKGN0b3IgWikpKSAoaW50LXR5cGUpKXxjdG9yOjE6YXJnOjEocGkgKGNhc2UgKGN0b3IgWikgKGN0b3IgWikgKGJyYW5jaCBQQzAgMCAoY3RvciBaKSkpIChkYXRhIE5hdCAoKSAoKSkpfGN0b3I6MTphcmc6MihwaSAoYXBwIChpbnQgMCkgKGludCAwKSkgKGludC10eXBlKSkjMTk=	pieces=ctor:0:arg:0::(pi (ctor S (ctor Z)) (data Nat () ()));;ctor:0:arg:1::(pi (data Equivalent ((data Nat () ())) ((ctor Z) (ctor Z))) (int-type));;ctor:0:arg:2::(pi (ctor reflexive (ctor Z)) (data Nat () ()));;ctor:1:arg:0::(pi (case (ctor reflexive (ctor Z)) (ctor Z) (branch reflexive 1 (ctor Z))) (int-type));;ctor:1:arg:1::(pi (case (ctor Z) (ctor Z) (branch PC0 0 (ctor Z))) (data Nat () ()));;ctor:1:arg:2::(pi (app (int 0) (int 0)) (int-type))
antigen-record	kind=def_group	assay=totality/diverging	label=diverging	seed=-	note=self-call arg is a projection → arg_relation :unknown	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAABbQAAAAFoam0AAAAFbmFtZXNsAAAAAW0AAAABaGo=	key=dG90YWxpdHkvZGl2ZXJnaW5nfHR5cGU6aChwaSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpfGJvZHk6aChsYW0gKGRhdGEgTmF0ICgpICgpKSAoY2FzZSAodmFyIDApIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGFwcCAoZ2xvYmFsIGgpIChjYXNlIChjdG9yIG1rX3BhaXIgKHZhciAxKSAodmFyIDEpKSAobGFtIChkYXRhIFNpZ21hICgoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggbWtfcGFpciAyICh2YXIgMSkpKSkpKSkjMjA=	pieces=type:h::(pi (data Nat () ()) (data Nat () ()));;body:h::(lam (data Nat () ()) (case (var 0) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (app (global h) (case (ctor mk_pair (var 1) (var 1)) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1)))))))
antigen-record	kind=def_group	assay=totality/terminating	label=terminating	seed=-	note=structural recursion with a rich call-free base branch	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAABbQAAAAFoam0AAAAFbmFtZXNsAAAAAW0AAAABaGo=	key=dG90YWxpdHkvdGVybWluYXRpbmd8dHlwZTpoKHBpIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSl8Ym9keTpoKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggWiAwIChjdG9yIG1rX3BhaXIgKGNhc2UgKHZhciAwKSAobGFtIChkYXRhIFNpZ21hICgoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggbWtfcGFpciAyICh2YXIgMSkpKSAoY3RvciBta19wYWlyIChjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBTaWdtYSAoKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIG1rX3BhaXIgMiAodmFyIDApKSkgKGN0b3IgbWtfcGFpciAoZGF0YSBFcXVpdmFsZW50ICgodmFyIDApKSAoKHZhciAwKSAodmFyIDApKSkgKGN0b3IgbWtfcGFpciAoY3RvciByZWZsZXhpdmUgKHZhciAwKSkgKGN0b3IgbWtfcGFpciAoYXBwIChjYXNlIChjdG9yIHJlZmxleGl2ZSAodmFyIDApKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKHZhciAwKSkgKGJyYW5jaCByZWZsZXhpdmUgMSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKHZhciAwKSkpKSAodmFyIDApKSAoY3RvciBta19wYWlyIChwaSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChjdG9yIG1rX3BhaXIgKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGFwcCAodmFyIDApICh2YXIgMCkpKSkpKSkpKSkgKGJyYW5jaCBTIDEgKGFwcCAoZ2xvYmFsIGgpICh2YXIgMCkpKSkpIzIx	pieces=type:h::(pi (data Nat () ()) (data Nat () ()));;body:h::(lam (data Nat () ()) (case (var 0) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor mk_pair (case (var 0) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1))) (ctor mk_pair (case (var 0) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 0))) (ctor mk_pair (data Equivalent ((var 0)) ((var 0) (var 0))) (ctor mk_pair (ctor reflexive (var 0)) (ctor mk_pair (app (case (ctor reflexive (var 0)) (lam (data Nat () ()) (var 0)) (branch reflexive 1 (lam (data Nat () ()) (var 0)))) (var 0)) (ctor mk_pair (pi (data Nat () ()) (data Nat () ())) (ctor mk_pair (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (app (var 0) (var 0)))))))))) (branch S 1 (app (global h) (var 0)))))
antigen-record	kind=def_group	assay=totality/diverging	label=diverging	seed=-	note=nullary mutual loop f = g, g = f (0×0 cross-function edges)	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAACbQAAAAFmbQAAAAFnam0AAAAFbmFtZXNsAAAAAm0AAAABZm0AAAABZ2o=	key=dG90YWxpdHkvZGl2ZXJnaW5nfHR5cGU6ZihkYXRhIE5hdCAoKSAoKSl8Ym9keTpmKGdsb2JhbCBnKXx0eXBlOmcoZGF0YSBOYXQgKCkgKCkpfGJvZHk6ZyhnbG9iYWwgZikjMjI=	pieces=type:f::(data Nat () ());;body:f::(global g);;type:g::(data Nat () ());;body:g::(global f)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Nl nat_lit!=nat_lit fast path (unify_one 1003, distinct)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmxjbQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChuYXQgMykjMjM=	pieces=idx:0::(nat 3)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=Tg tg0 [1] — int-literal heads agree (undecided)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADdGcwbQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACVGdtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChpbnQgMSkjMjQ=	pieces=idx:0::(int 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Foo MkFoo vs rigid Z index — genuine S/Z clash (S9 control)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFTWtGb29tAAAACGN0eF92YXJzYQJtAAAABWRuYW1lbQAAAANGb29tAAAAC3BhcmFtX2NvdW50YQE=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopfHBhcmFtOjAodmFyIDEpIzI1	pieces=idx:0::(ctor Z);;param:0::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=SpineU stuck plus-application spine element — unify_spine :undecided drop (1047)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADc3B1bQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAAGU3BpbmVVbQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKGN0b3IgWikpIzI2	pieces=idx:0::(ctor S (ctor Z))
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Sq mksq [var0,var1] — forced equation (Solution step)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtzcW0AAAAIY3R4X3ZhcnNhAm0AAAAFZG5hbWVtAAAAAlNxbQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8aWR4OjEodmFyIDEpIzI3	pieces=idx:0::(var 0);;idx:1::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Foo MkFoo over a free index — param in result-index spine is SOLVABLE (S9)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFTWtGb29tAAAACGN0eF92YXJzYQJtAAAABWRuYW1lbQAAAANGb29tAAAAC3BhcmFtX2NvdW50YQE=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8cGFyYW06MCh2YXIgMSkjMjg=	pieces=idx:0::(var 0);;param:0::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Ty tnat [Type0] — rigid data/Type clash	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEdG5hdG0AAAAIY3R4X3ZhcnNhAG0AAAAFZG5hbWVtAAAAAlR5bQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh0eXBlIDApIzI5	pieces=idx:0::(type 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=Nl nat_lit result index vs ctor-tower scrutinee — peel nat_lit->ctor (unify_one 1005/1006)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmxjbQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpIzMw	pieces=idx:0::(ctor S (ctor S (ctor Z)))
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=bad_motive	seed=-	note=motive = an opaque outer variable — apply_motive_checked's :vneutral arm keeps applying (kernel.ex:634); the motive never becomes a well-typed Pi, so infer still rejects with :bad_motive	scaffold=g3QAAAABbQAAAAxtb3RpdmVfcHJvYmVtAAAAB25ldXRyYWw=	key=YnJhbmNodW5pZnkvdmVyZGljdHwjMzE=	pieces=
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Cyc4b interleaved crossing — union-find self-loop collapse (bind_index 1073)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAGbWtjeWMybQAAAAhjdHhfdmFyc2ECbQAAAAVkbmFtZW0AAAAFQ3ljNGJtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8aWR4OjEodmFyIDEpfGlkeDoyKHZhciAxKXxpZHg6Myh2YXIgMCkjMzI=	pieces=idx:0::(var 0);;idx:1::(var 1);;idx:2::(var 1);;idx:3::(var 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=bad_motive	seed=-	note=motive = a concrete non-function value (a Nat type-value) — apply_motive_checked halts on the very first application, its catch-all arm (kernel.ex:635)	scaffold=g3QAAAABbQAAAAxtb3RpdmVfcHJvYmVtAAAABm5vbmZ1bg==	key=YnJhbmNodW5pZnkvdmVyZGljdHwjMzM=	pieces=
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Cyc4 crossing — multi-key cycle collapse	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFbWtjeWNtAAAACGN0eF92YXJzYQJtAAAABWRuYW1lbQAAAARDeWM0bQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8aWR4OjEodmFyIDEpfGlkeDoyKHZhciAxKXxpZHg6Myh2YXIgMCkjMzQ=	pieces=idx:0::(var 0);;idx:1::(var 1);;idx:2::(var 1);;idx:3::(var 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Sq mksq [Z,S Z] — merge conflict	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtzcW0AAAAIY3R4X3ZhcnNhAG0AAAAFZG5hbWVtAAAAAlNxbQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopfGlkeDoxKGN0b3IgUyAoY3RvciBaKSkjMzU=	pieces=idx:0::(ctor Z);;idx:1::(ctor S (ctor Z))
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Cyc1 self-cycle — param buries into own successor, occurs-check (var_cycle? 1028/1038)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFaWRjeWNtAAAACGN0eF92YXJzYQFtAAAABWRuYW1lbQAAAARDeWMxbQAAAAtwYXJhbV9jb3VudGEB	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKHZhciAwKSl8cGFyYW06MCh2YXIgMCkjMzY=	pieces=idx:0::(ctor S (var 0));;param:0::(var 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Dboth nested :data result index (ps and is both non-empty) — subst_params :data recursion (953), rigid head clash	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAGbWtib3RobQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAAFRGJvdGhtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopIzM3	pieces=idx:0::(ctor Z)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=CaseIdx :case-headed result index — subst_params :case recursion (960/961)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtjaW0AAAAIY3R4X3ZhcnNhAG0AAAAFZG5hbWVtAAAAB0Nhc2VJZHhtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopIzM4	pieces=idx:0::(ctor Z)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=Nl ctor-tower result index vs nat_lit scrutinee — peel ctor->nat_lit (unify_one 1008/1009)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmx0bQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChuYXQgMSkjMzk=	pieces=idx:0::(nat 1)
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): transport body ill-typed (Nat motive, Bd body)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShhcHAgKGNhc2UgKGN0b3IgcmVmbGV4aXZlIChkYXRhIE5hdCAoKSAoKSkgKGN0b3IgWikpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBOYXQgKCkgKCkpKSAoKHZhciAxKSAodmFyIDApKSkgKHBpIChhcHAgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpICh2YXIgMikpIChhcHAgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpICh2YXIgMikpKSkpKSAoYnJhbmNoIHJlZmxleGl2ZSAxIChsYW0gKGFwcCAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGN0b3IgWikpICh2YXIgMCkpKSkgKGN0b3IgRikpIzQw	pieces=term::(app (case (ctor reflexive (data Nat () ()) (ctor Z)) (lam (data Nat () ()) (lam (data Nat () ()) (lam (data Equivalent ((data Nat () ())) ((var 1) (var 0))) (pi (app (lam (data Nat () ()) (data Nat () ())) (var 2)) (app (lam (data Nat () ()) (data Nat () ())) (var 2)))))) (branch reflexive 1 (lam (app (lam (data Nat () ()) (data Nat () ())) (ctor Z)) (var 0)))) (ctor F))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): unknown ctor	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjdG9yIG5vc3VjaGN0b3IpIzQx	pieces=term::(ctor nosuchctor)
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): unknown global	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShnbG9iYWwgbm9zdWNoZGVmKSM0Mg==	pieces=term::(global nosuchdef)
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case scrutinee not data	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChmbG9hdCAtMC41KSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkpIzQz	pieces=term::(case (float -0.5) (lam (data Nat () ()) (data Nat () ())))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): unknown family	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShkYXRhIE5vU3VjaEZhbWlseSAoKSAoKSkjNDQ=	pieces=term::(data NoSuchFamily () ())
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case with unknown-ctor branch	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGN0b3IgWikpIChicmFuY2ggbm9zdWNoY3RvciAwIChjdG9yIFopKSkjNDU=	pieces=term::(case (ctor Z) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)) (branch nosuchctor 0 (ctor Z)))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case motive returns an unknown family	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOb1N1Y2hGYW1pbHkgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGN0b3IgWikpKSM0Ng==	pieces=term::(case (ctor Z) (lam (data Nat () ()) (data NoSuchFamily () ())) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=nvar vs napp head mismatch (146)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgMCl8dDIoYXBwICh2YXIgMSkgKHR5cGUgMCkpIzQ3	pieces=t1::(var 0);;t2::(app (var 1) (type 0))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=S/Z tower vs compact-lit (91)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpfHQyKG5hdCAyKSM0OA==	pieces=t1::(ctor S (ctor S (ctor Z)));;t2::(nat 2)
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=case first vs second component, branch-body mismatch (150)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBTaWdtYSAoKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIG1rX3BhaXIgMiAodmFyIDEpKSl8dDIoY2FzZSAodmFyIDApIChsYW0gKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBta19wYWlyIDIgKHZhciAwKSkpIzQ5	pieces=t1::(case (var 0) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1)));;t2::(case (var 0) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vtype (187)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAodHlwZSAwKSl8dDIoYXBwICh2YXIgMCkgKHR5cGUgMCkpIzUw	pieces=t1::(app (var 0) (type 0));;t2::(app (var 0) (type 0))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=η neutral-vs-λ (70,108)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgMCl8dDIobGFtICh0eXBlIDApIChhcHAgKHZhciAxKSAodmFyIDApKSkjNTE=	pieces=t1::(var 0);;t2::(lam (type 0) (app (var 1) (var 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=compact-nat distinct literals (85)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShuYXQgMil8dDIobmF0IDMpIzUy	pieces=t1::(nat 2);;t2::(nat 3)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=compact-lit vs S/Z tower (88)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShuYXQgMSl8dDIoY3RvciBTIChjdG9yIFopKSM1Mw==	pieces=t1::(nat 1);;t2::(ctor S (ctor Z))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=λ-vs-non-λ (109)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShsYW0gKHR5cGUgMCkgKHZhciAxKSl8dDIodHlwZSAwKSM1NA==	pieces=t1::(lam (type 0) (var 1));;t2::(type 0)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vfloat_type (190)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZmxvYXQtdHlwZSkpfHQyKGFwcCAodmFyIDApIChmbG9hdC10eXBlKSkjNTU=	pieces=t1::(app (var 0) (float-type));;t2::(app (var 0) (float-type))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vλ fallback → conv_struct η (199)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAobGFtICh0eXBlIDApICh0eXBlIDApKSl8dDIoYXBwICh2YXIgMCkgKGxhbSAodHlwZSAwKSAodHlwZSAwKSkpIzU2	pieces=t1::(app (var 0) (lam (type 0) (type 0)));;t2::(app (var 0) (lam (type 0) (type 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vint (189)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoaW50IC03KSl8dDIoYXBwICh2YXIgMCkgKGludCAtNykpIzU3	pieces=t1::(app (var 0) (int -7));;t2::(app (var 0) (int -7))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=out-of-ctx var → neutral (eval)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgNSl8dDIodmFyIDUpIzU4	pieces=t1::(var 5);;t2::(var 5)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vint_type (188)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoaW50LXR5cGUpKXx0MihhcHAgKHZhciAwKSAoaW50LXR5cGUpKSM1OQ==	pieces=t1::(app (var 0) (int-type));;t2::(app (var 0) (int-type))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vnat no-δ fast path (194)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAobmF0IDMpKXx0MihhcHAgKHZhciAwKSAobmF0IDMpKSM2MA==	pieces=t1::(app (var 0) (nat 3));;t2::(app (var 0) (nat 3))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vdata (193)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZGF0YSBOYXQgKCkgKCkpKXx0MihhcHAgKHZhciAwKSAoZGF0YSBOYXQgKCkgKCkpKSM2MQ==	pieces=t1::(app (var 0) (data Nat () ()));;t2::(app (var 0) (data Nat () ()))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vfloat (191)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZmxvYXQgMy4wKSl8dDIoYXBwICh2YXIgMCkgKGZsb2F0IDMuMCkpIzYy	pieces=t1::(app (var 0) (float 3.0));;t2::(app (var 0) (float 3.0))
antigen-record	kind=check_mode	assay=check/verdict	label=reject	seed=-	note=check nosuchctor : List Nat — checking-mode unknown constructor (unknown_ctor)	scaffold=g3QAAAABbQAAAAhjdHhfdmFyc2EA	key=Y2hlY2svdmVyZGljdHx0ZXJtKGN0b3Igbm9zdWNoY3Rvcil8dHlwZShkYXRhIExpc3QgKChkYXRhIE5hdCAoKSAoKSkpICgpKSM2Mw==	pieces=term::(ctor nosuchctor);;type::(data List ((data Nat () ())) ())
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :mode must be :whnf|:nf (rejects a valid :delta atom used as :mode)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncEbW9kZXcJY2VydGlmaWVkag==	key=ZGVsdGEvbmZ8IzY0	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=δ+ι: snd kpair → S Z (project second via ι-on-case)	scaffold=-	key=ZGVsdGEvbmZ8dGVybShjYXNlIChnbG9iYWwga3BhaXIpIChsYW0gKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBta19wYWlyIDIgKHZhciAwKSkpfGV4cGVjdGVkKGN0b3IgUyAoY3RvciBaKSkjNjU=	pieces=term::(case (global kpair) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 0)));;expected::(ctor S (ctor Z))
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=ncase/branch_miss (unfolded): donly (S Z) unfolds to a case with no S arm — reduce_unfolded freezes it, never crashes	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGdsb2JhbCBkb25seSkgKGN0b3IgUyAoY3RvciBaKSkpfGV4cGVjdGVkKGFwcCAoZ2xvYmFsIGRvbmx5KSAoY3RvciBTIChjdG9yIFopKSkjNjY=	pieces=term::(app (global donly) (ctor S (ctor Z)));;expected::(app (global donly) (ctor S (ctor Z)))
antigen-record	kind=delta_reduce	assay=delta/nf	label=fuel_probe	seed=-	note=fuel/exhausted: idnat^3 Z needs 3 δ-steps; a 2-step budget reports :fuel_exhausted, never a truncated wrong value	scaffold=g3QAAAACbQAAAARvcHRzbAAAAAFoAncEZnVlbGECam0AAAAEd2FudHcOZnVlbF9leGhhdXN0ZWQ=	key=ZGVsdGEvbmZ8dGVybShhcHAgKGdsb2JhbCBpZG5hdCkgKGFwcCAoZ2xvYmFsIGlkbmF0KSAoYXBwIChnbG9iYWwgaWRuYXQpIChjdG9yIFopKSkpfGV4cGVjdGVkKGN0b3IgWikjNjc=	pieces=term::(app (global idnat) (app (global idnat) (app (global idnat) (ctor Z))));;expected::(ctor Z)
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/struct_eq: struct_eq Int 3 4 → False (δ-fold via the audited literal table)	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoYXBwIChnbG9iYWwgc3RydWN0X2VxKSAoaW50LXR5cGUpKSAoaW50IDMpKSAoaW50IDQpKXxleHBlY3RlZChjdG9yIEZhbHNlKSM2OA==	pieces=term::(app (app (app (global struct_eq) (int-type)) (int 3)) (int 4));;expected::(ctor False)
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/arity_stuck: struct_eq Int 5 (unsaturated, 2 of 3 args) stays neutral — never a bogus fold	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoZ2xvYmFsIHN0cnVjdF9lcSkgKGludC10eXBlKSkgKGludCA1KSl8ZXhwZWN0ZWQoYXBwIChhcHAgKGdsb2JhbCBzdHJ1Y3RfZXEpIChpbnQtdHlwZSkpIChpbnQgNSkpIzY5	pieces=term::(app (app (global struct_eq) (int-type)) (int 5));;expected::(app (app (global struct_eq) (int-type)) (int 5))
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/struct_ne: struct_ne Int 5 5 → False (δ-fold via the audited literal table)	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoYXBwIChnbG9iYWwgc3RydWN0X25lKSAoaW50LXR5cGUpKSAoaW50IDUpKSAoaW50IDUpKXxleHBlY3RlZChjdG9yIEZhbHNlKSM3MA==	pieces=term::(app (app (app (global struct_ne) (int-type)) (int 5)) (int 5));;expected::(ctor False)
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :delta must be :certified|:none (rejects a valid :mode atom used as :delta)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncFZGVsdGF3BHdobmZq	key=ZGVsdGEvbmZ8Izcx	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :fuel must be a positive integer or :infinity (0 is rejected)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncEZnVlbGEAag==	key=ZGVsdGEvbmZ8Izcy	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=ncase/branch_miss (direct): case (idnat (S Z)) {Z->Z} has no S arm — unfold_certified_head freezes it, never crashes	scaffold=-	key=ZGVsdGEvbmZ8dGVybShjYXNlIChhcHAgKGdsb2JhbCBpZG5hdCkgKGN0b3IgUyAoY3RvciBaKSkpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkpfGV4cGVjdGVkKGNhc2UgKGFwcCAoZ2xvYmFsIGlkbmF0KSAoY3RvciBTIChjdG9yIFopKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggWiAwIChjdG9yIFopKSkjNzM=	pieces=term::(case (app (global idnat) (ctor S (ctor Z))) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)));;expected::(case (app (global idnat) (ctor S (ctor Z))) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)))
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :stuck_cases must be :preserve (any other value is rejected — MatchError, rescued and re-raised)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncLc3R1Y2tfY2FzZXN3BWZhbHNlag==	key=ZGVsdGEvbmZ8Izc0	pieces=
antigen-record	kind=dot_forcing	assay=forcing/dot	label=reject	seed=-	note=Sq mksq {n=.(S Z)} vs forced Z — multi-index reject	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtzcW0AAAAIY3R4X3ZhcnNhAG0AAAAGZmFtaWx5bQAAAAJTcW0AAAAEbmFtZW0AAAABbg==	key=Zm9yY2luZy9kb3R8aWR4OjAoY3RvciBaKXxpZHg6MShjdG9yIFopfHdyaXR0ZW4oY3RvciBTIChjdG9yIFopKSM3NQ==	pieces=idx:0::(ctor Z);;idx:1::(ctor Z);;written::(ctor S (ctor Z))
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAADNSA2	key=c2VyaWFsaXplL2RlY29kZXwjNzY=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAFKDUgNik=	key=c2VyaWFsaXplL2RlY29kZXwjNzc=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAABKQ==	key=c2VyaWFsaXplL2RlY29kZXwjNzg=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAELTIuMA==	key=c2VyaWFsaXplL2RlY29kZXwjNzk=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAACLTM=	key=c2VyaWFsaXplL2RlY29kZXwjODA=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAaKGNhc2UgKHZhciAwKSAodmFyIDApIGZvbyk=	key=c2VyaWFsaXplL2RlY29kZXwjODE=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAADZm9v	key=c2VyaWFsaXplL2RlY29kZXwjODI=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAKKGhvbGUgImgiKQ==	key=c2VyaWFsaXplL2RlY29kZXwjODM=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAFKHp6eik=	key=c2VyaWFsaXplL2RlY29kZXwjODQ=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAIKGFic3VyZCk=	key=c2VyaWFsaXplL2RlY29kZXwjODU=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAABKA==	key=c2VyaWFsaXplL2RlY29kZXwjODY=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAGImFcImIi	key=c2VyaWFsaXplL2RlY29kZXwjODc=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAA	key=c2VyaWFsaXplL2RlY29kZXwjODg=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAQKGN0b3IgRm9vICh6enopKQ==	key=c2VyaWFsaXplL2RlY29kZXwjODk=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAEImFiYw==	key=c2VyaWFsaXplL2RlY29kZXwjOTA=	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAApKGNhc2UgKHZhciAwKSAodmFyIDApIChicmFuY2ggWiAwICh6enopKSk=	key=c2VyaWFsaXplL2RlY29kZXwjOTE=	pieces=
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=type former	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3x0eXBlKHR5cGUgMCl8dGVybShkYXRhIFNpZ21hICgoZmxvYXQtdHlwZSkgKGxhbSAoZmxvYXQtdHlwZSkgKGZsb2F0LXR5cGUpKSkgKCkpIzky	pieces=type::(type 0);;term::(data Sigma ((float-type) (lam (float-type) (float-type))) ())
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=parameterized wrong result-param arity	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAACcGNtAAAACnF1YW50aXRpZXNsAAAAAW0AAAAEbWFueWptAAAACnJpZHhfY291bnRhAW0AAAAMcnBhcmFtX2NvdW50YQBqbQAAAA9mYW1faW5kZXhfbmFtZXNsAAAAAW0AAAABbmptAAAACWZhbV9sZXZlbGEAbQAAAAhmYW1fbmFtZW0AAAABUG0AAAAPZmFtX3BhcmFtX25hbWVzbAAAAAFtAAAAAWFq	key=dW5pdmVyc2VzfGZhbV9wYXJhbTowKHR5cGUgMCl8ZmFtX2luZGV4OjAoaW50LXR5cGUpfGN0b3I6MDphcmc6MCh2YXIgMCl8Y3RvcjowOnJpZHg6MChpbnQgLTIpIzkz	pieces=fam_param:0::(type 0);;fam_index:0::(int-type);;ctor:0:arg:0::(var 0);;ctor:0:ridx:0::(int -2)
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=parameterized non-uniform (result param = x)	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAACcGNtAAAACnF1YW50aXRpZXNsAAAAAW0AAAAEbWFueWptAAAACnJpZHhfY291bnRhAW0AAAAMcnBhcmFtX2NvdW50YQFqbQAAAA9mYW1faW5kZXhfbmFtZXNsAAAAAW0AAAABbmptAAAACWZhbV9sZXZlbGEAbQAAAAhmYW1fbmFtZW0AAAABUG0AAAAPZmFtX3BhcmFtX25hbWVzbAAAAAFtAAAAAWFq	key=dW5pdmVyc2VzfGZhbV9wYXJhbTowKHR5cGUgMCl8ZmFtX2luZGV4OjAoZmxvYXQtdHlwZSl8Y3RvcjowOmFyZzowKHZhciAwKXxjdG9yOjA6cmlkeDowKGZsb2F0IC00LjUpfGN0b3I6MDpycGFyYW06MCh2YXIgMCkjOTQ=	pieces=fam_param:0::(type 0);;fam_index:0::(float-type);;ctor:0:arg:0::(var 0);;ctor:0:ridx:0::(float -4.5);;ctor:0:rparam:0::(var 0)
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=arg-bearing ctor with non-type field	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAADbWtpbQAAAApxdWFudGl0aWVzbAAAAAFtAAAAB3ByZXNlbnRqbQAAAApyaWR4X2NvdW50YQFtAAAADHJwYXJhbV9jb3VudGEAam0AAAAPZmFtX2luZGV4X25hbWVzbAAAAAFtAAAAAW5qbQAAAAlmYW1fbGV2ZWxhAG0AAAAIZmFtX25hbWVtAAAABElkeEltAAAAD2ZhbV9wYXJhbV9uYW1lc2o=	key=dW5pdmVyc2VzfGZhbV9pbmRleDowKGZsb2F0LXR5cGUpfGN0b3I6MDphcmc6MChmbG9hdCAwLjApfGN0b3I6MDpyaWR4OjAoZmxvYXQgLTEuNSkjOTU=	pieces=fam_index:0::(float-type);;ctor:0:arg:0::(float 0.0);;ctor:0:ridx:0::(float -1.5)
antigen-record	kind=elab_program	assay=elab/metamorphic	label=none	seed=-	note=computed_idx/rebuild invariant under alpha_rename	scaffold=g3QAAAAEbQAAAAhiYXNlX3NyY20AAAGSbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNMaXN0ID0gU05pbCB8IFNDb25zKE5hdCwgU0xpc3QpCiAgZm4gYXBwKHhzOiBTTGlzdCwgeXM6IFNMaXN0KSAtPiBTTGlzdCA9IG1hdGNoIHhzCiAgICBTTmlsKCkgLT4geXMKICAgIFNDb25zKGgsIHQpIC0+IFNDb25zKGgsIGFwcCh0LCB5cykpCiAgdHlwZSBGIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGxlYWYgOiBGKFNOaWwoKSkKICAgIG1rIDogRihhcykgLT4gRihicykgLT4gRihhcHAoYXMsIGJzKSkKICBmbiBnKHtwOiBTTGlzdH0sIHtxOiBTTGlzdH0sIHY6IEYoYXBwKHAsIHEpKSkgLT4gRihhcHAocCwgcSkpID0KICAgIG1hdGNoIHYKICAgICAgbGVhZigpIC0+IGxlYWYoKQogICAgICBtayhsLCByKSAtPiBtayhsLCByKQplbmQKbQAAAAJpZG0AAAAUY29tcHV0ZWRfaWR4L3JlYnVpbGRtAAAACXRyYW5zZm9ybW0AAAAMYWxwaGFfcmVuYW1lbQAAAAt2YXJpYW50X3NyY20AAAGWbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNMaXN0ID0gU05pbCB8IFNDb25zKE5hdCwgU0xpc3QpCiAgZm4gYXBwKHhzOiBTTGlzdCwgeXM6IFNMaXN0KSAtPiBTTGlzdCA9IG1hdGNoIHhzCiAgICBTTmlsKCkgLT4geXMKICAgIFNDb25zKGgsIHQpIC0+IFNDb25zKGgsIGFwcCh0LCB5cykpCiAgdHlwZSBGIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGxlYWYgOiBGKFNOaWwoKSkKICAgIG1rIDogRihhcykgLT4gRihicykgLT4gRihhcHAoYXMsIGJzKSkKICBmbiBnKHtwOiBTTGlzdH0sIHtxOiBTTGlzdH0sIHZ2MDogRihhcHAocCwgcSkpKSAtPiBGKGFwcChwLCBxKSkgPQogICAgbWF0Y2ggdnYwCiAgICAgIGxlYWYoKSAtPiBsZWFmKCkKICAgICAgbWsobCwgcikgLT4gbWsobCwgcikKZW5kCg==	key=ZWxhYi9tZXRhbW9ycGhpY3wjOTY=	pieces=
antigen-record	kind=elab_program	assay=elab/completeness	label=well_typed	seed=-	note=goal Equivalent(NV(n), v, v), reflexive(v)	scaffold=g3QAAAACbQAAAAJpZG0AAAAXZXFfdmFsdWUvdmFyL3JlZmxfc2NydXRtAAAAA3NyY20AAAHUbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNOYXQgaW5kaWNlcyAobjogTmF0KQogICAgc3plcm8gOiBTTmF0KFopCiAgICBzc3VjIDogU05hdChuKSAtPiBTTmF0KFMobikpCiAgdHlwZSBOViBpbmRpY2VzIChuOiBOYXQpCiAgICB2eiA6IE5WKFopCiAgICB2cyA6IFNOYXQobikgLT4gTlYoUyhuKSkKICBmbiB0b1MobTogTmF0KSAtPiBTTmF0KG0pID0gbWF0Y2ggbQogICAgWigpIC0+IHN6ZXJvKCkKICAgIFMoaikgLT4gc3N1Yyh0b1MoaikpCiAgZm4gdmlldyhuOiBOYXQpIC0+IE5WKG4pID0gbWF0Y2ggbgogICAgWigpIC0+IHZ6KCkKICAgIFMobSkgLT4gdnModG9TKG0pKQogIGZuIGYoe246IE5hdH0sIHY6IE5WKG4pKSAtPiBFcXVpdmFsZW50KE5WKG4pLCB2LCB2KSA9CiAgICBtYXRjaCB2CiAgICAgIHZ6KCkgLT4gcmVmbGV4aXZlKHYpCiAgICAgIHZzKHMpIC0+IHJlZmxleGl2ZSh2KQplbmQK	key=ZWxhYi9jb21wbGV0ZW5lc3N8Izk3	pieces=
antigen-record	kind=elab_program	assay=elab/dot_forcing	label=accept	seed=-	note=right dot on the plain dispatch path (landed C-b shape)	scaffold=g3QAAAADbQAAAAZleHBlY3R3BmFjY2VwdG0AAAACaWRtAAAAEmZvcmNlZC9wbGFpbi9yaWdodG0AAAADc3JjbQAAASttb2QgUAogIHR5cGUgTmF0ID0gWiB8IFMoTmF0KQogIHR5cGUgVmVjKGE6IFR5cGUpIGluZGljZXMgKG46IE5hdCkKICAgIHZuaWwgOiBWZWMoYSwgWikKICAgIHZjb25zIDogYSAtPiBWZWMoYSwgbikgLT4gVmVjKGEsIFMobikpCiAgdHlwZSBQYWNrKGE6IFR5cGUpIGluZGljZXMgKCkKICAgIHBrIDogVmVjKGEsIG0pIC0+IFBhY2soYSkKICBmbiBmKHthOiBUeXBlfSwge2s6IE5hdH0sIHY6IFZlYyhhLCBTKGspKSkgLT4gVmVjKGEsIFMoaykpID0gbWF0Y2ggdgogICAgdmNvbnMoe24gPSAua30sIGgsIHQpIC0+IHYKZW5kCg==	key=ZWxhYi9kb3RfZm9yY2luZ3wjOTg=	pieces=
antigen-record	kind=elab_program	assay=elab/dot_forcing	label=accept	seed=-	note=right dot on the carried-eq path (over-rejection guard)	scaffold=g3QAAAADbQAAAAZleHBlY3R3BmFjY2VwdG0AAAACaWRtAAAAFGZvcmNlZC9jYXJyaWVkL3JpZ2h0bQAAAANzcmNtAAABpG1vZCBQCiAgdHlwZSBOYXQgPSBaIHwgUyhOYXQpCiAgdHlwZSBTTGlzdCA9IFNOaWwgfCBTQ29ucyhOYXQsIFNMaXN0KQogIGZuIGFwcCh4czogU0xpc3QsIHlzOiBTTGlzdCkgLT4gU0xpc3QgPSBtYXRjaCB4cwogICAgU05pbCgpIC0+IHlzCiAgICBTQ29ucyhoLCB0KSAtPiBTQ29ucyhoLCBhcHAodCwgeXMpKQogIHR5cGUgSCBpbmRpY2VzIChuOiBOYXQsIHhzOiBTTGlzdCkKICAgIGhtayA6IEgoUyhtKSwgYXBwKGFzLCBicykpCiAgdHlwZSBHIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGd3cmFwIDogRyhjcykKICBmbiBnKHtqOiBOYXR9LCB7cDogU0xpc3R9LCB7cTogU0xpc3R9LCB2OiBIKFMoaiksIGFwcChwLCBxKSksIHc6IEcoYXBwKHAsIHEpKSkgLT4gTmF0ID0gbWF0Y2ggdgogICAgaG1rKHttID0gLmp9KSAtPiBaKCkKZW5kCg==	key=ZWxhYi9kb3RfZm9yY2luZ3wjOTk=	pieces=
antigen-record	kind=elab_program	assay=elab/soundness	label=well_typed	seed=-	note=boolean literal in inference position — Kernel.bool_type_value/1	scaffold=g3QAAAACbQAAAAJpZG0AAAAVbGl0X3R5cGluZy9ib29sX2luZmVybQAAAANzcmNtAAAAJW1vZCBQCiAgZm4gZmxhZygpIC0+IEJvb2wgPSB0cnVlCmVuZAo=	key=ZWxhYi9zb3VuZG5lc3N8IzEwMA==	pieces=
antigen-record	kind=family	assay=inductive/env_roundtrip	label=well_typed	seed=-	note=Env-accessor roundtrip probe (AntigenEnv/antigenA, n=3)	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAACbQAAAAF4bQAAAAF5am0AAAAEbmFtZW0AAAAIYW50aWdlbkFtAAAACnF1YW50aXRpZXNsAAAAAm0AAAAGZXJhc2VkbQAAAAdwcmVzZW50am0AAAAKcmlkeF9jb3VudGEBbQAAAAxycGFyYW1fY291bnRhAWptAAAAD2ZhbV9pbmRleF9uYW1lc2wAAAABbQAAAAFuam0AAAAJZmFtX2xldmVsYQBtAAAACGZhbV9uYW1lbQAAAApBbnRpZ2VuRW52bQAAAA9mYW1fcGFyYW1fbmFtZXNsAAAAAW0AAAABYWo=	key=aW5kdWN0aXZlL2Vudl9yb3VuZHRyaXB8ZmFtX3BhcmFtOjAodHlwZSAwKXxmYW1faW5kZXg6MChpbnQtdHlwZSl8Y3RvcjowOmFyZzowKHZhciAwKXxjdG9yOjA6YXJnOjEodmFyIDEpfGN0b3I6MDpyaWR4OjAoaW50IDMpfGN0b3I6MDpycGFyYW06MCh2YXIgMikjMTAx	pieces=fam_param:0::(type 0);;fam_index:0::(int-type);;ctor:0:arg:0::(var 0);;ctor:0:arg:1::(var 1);;ctor:0:ridx:0::(int 3);;ctor:0:rparam:0::(var 2)
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2d0KSAoZmxvYXQgNC41KSkgKGZsb2F0IC0zLjUpKSMxMDI=	pieces=type::(data Bool () ());;term::(app (app (global float_gt) (float 4.5)) (float -3.5))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChhcHAgKGdsb2JhbCBzdHJ1Y3RfbmUpIChmbG9hdC10eXBlKSkgKGZsb2F0IC0zLjApKSAoZmxvYXQgLTMuNzUpKSMxMDM=	pieces=type::(data Bool () ());;term::(app (app (app (global struct_ne) (float-type)) (float -3.0)) (float -3.75))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBWZWMgKCkgKCh2YXIgMCkpKXxjdHgxKGRhdGEgTmF0ICgpICgpKXx0eXBlKGZsb2F0LXR5cGUpfHRlcm0oY2FzZSAodmFyIDApIChsYW0gKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIFZlYyAoKSAoKHZhciAwKSkpIChmbG9hdC10eXBlKSkpIChicmFuY2ggdm5pbCAwIChmbG9hdCAtMi41KSkgKGJyYW5jaCB2Y29ucyAzIChmbG9hdCAxLjApKSkjMTA0	pieces=ctx0::(data Vec () ((var 0)));;ctx1::(data Nat () ());;type::(float-type);;term::(case (var 0) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (float-type))) (branch vnil 0 (float -2.5)) (branch vcons 3 (float 1.0)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfZXEpIChmbG9hdCAtMC43NSkpIChmbG9hdCAtMi41KSkjMTA1	pieces=type::(data Bool () ());;term::(app (app (global float_eq) (float -0.75)) (float -2.5))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9sdCkgKGFwcCAoYXBwIChnbG9iYWwgaW50X3JlbSkgKGludCAtNykpIChpbnQgMCkpKSAoaW50IDkpKSMxMDY=	pieces=type::(data Bool () ());;term::(app (app (global int_lt) (app (app (global int_rem) (int -7)) (int 0))) (int 9))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQNtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnxjdHgwKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkpICgoY3RvciBta19wYWlyICh2YXIgMSkgKHZhciAxKSkgKGN0b3IgbWtfcGFpciAodmFyIDEpICh2YXIgMSkpKSl8Y3R4MShkYXRhIFZlYyAoKSAoKHZhciAwKSkpfGN0eDIoZGF0YSBOYXQgKCkgKCkpfHR5cGUoZGF0YSBOYXQgKCkgKCkpfHRlcm0oY2FzZSAodmFyIDEpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIFZlYyAoKSAoKHZhciAwKSkpIChkYXRhIE5hdCAoKSAoKSkpKSAoYnJhbmNoIHZuaWwgMCAoY3RvciBTIChjdG9yIFopKSkgKGJyYW5jaCB2Y29ucyAzIChjdG9yIFMgKGN0b3IgUyAoY3RvciBTIChjdG9yIFopKSkpKSkjMTA3	pieces=ctx0::(data Equivalent ((data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ())) ((ctor mk_pair (var 1) (var 1)) (ctor mk_pair (var 1) (var 1))));;ctx1::(data Vec () ((var 0)));;ctx2::(data Nat () ());;type::(data Nat () ());;term::(case (var 1) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (data Nat () ()))) (branch vnil 0 (ctor S (ctor Z))) (branch vcons 3 (ctor S (ctor S (ctor S (ctor Z))))))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgTmF0ICgpICgpKSkgKChjdG9yIFMgKGN0b3IgWikpIChjdG9yIFMgKGN0b3IgWikpKSl8dGVybShhcHAgKGxhbSAoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBOYXQgKCkgKCkpKSAoKGN0b3IgUyAoY3RvciBaKSkgKGN0b3IgUyAoY3RvciBaKSkpKSAodmFyIDApKSAoY3RvciByZWZsZXhpdmUgKGRhdGEgTmF0ICgpICgpKSAoY3RvciBTIChjdG9yIFopKSkpIzEwOA==	pieces=type::(data Equivalent ((data Nat () ())) ((ctor S (ctor Z)) (ctor S (ctor Z))));;term::(app (lam (data Equivalent ((data Nat () ())) ((ctor S (ctor Z)) (ctor S (ctor Z)))) (var 0)) (ctor reflexive (data Nat () ()) (ctor S (ctor Z))))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoaW50LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBpbnRfcmVtKSAoaW50IC0xOCkpIChhcHAgKGFwcCAoZ2xvYmFsIGludF9yZW0pIChpbnQgLTkpKSAoaW50IC0xOCkpKSMxMDk=	pieces=type::(int-type);;term::(app (app (global int_rem) (int -18)) (app (app (global int_rem) (int -9)) (int -18)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBOYXQgKCkgKCkpfHRlcm0oY2FzZSAobmF0IDApIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKHZhciAwKSkpIzExMA==	pieces=type::(data Nat () ());;term::(case (nat 0) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (var 0)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoaW50LXR5cGUpfHR5cGUodHlwZSAwKXx0ZXJtKGRhdGEgRXF1aXZhbGVudCAoKGludC10eXBlKSkgKChhcHAgKGFwcCAoZ2xvYmFsIGludF9tdWwpICh2YXIgMCkpIChpbnQgLTgpKSAoYXBwIChhcHAgKGdsb2JhbCBpbnRfbXVsKSAodmFyIDApKSAoaW50IC04KSkpKSMxMTE=	pieces=ctx0::(int-type);;type::(type 0);;term::(data Equivalent ((int-type)) ((app (app (global int_mul) (var 0)) (int -8)) (app (app (global int_mul) (var 0)) (int -8))))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBUeSAoKSAoKGRhdGEgQmQgKCkgKCkpKSl8dHlwZShkYXRhIE5hdCAoKSAoKSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSAodHlwZSAwKSAobGFtIChkYXRhIFR5ICgpICgodmFyIDApKSkgKGRhdGEgTmF0ICgpICgpKSkpIChicmFuY2ggdG5hdCAwIChjdG9yIFopKSAoYnJhbmNoIHRiZCAwIChjdG9yIFopKSAoYnJhbmNoIHRpbnQgMCAoY3RvciBaKSkgKGJyYW5jaCB0Zmx0IDAgKGN0b3IgWikpIChicmFuY2ggdHBpIDAgKGN0b3IgWikpIChicmFuY2ggdHNpZyAwIChjdG9yIFopKSAoYnJhbmNoIHR2ZWMgMCAoY3RvciBaKSkpIzExMg==	pieces=ctx0::(data Ty () ((data Bd () ())));;type::(data Nat () ());;term::(case (var 0) (lam (type 0) (lam (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor Z)) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X2d0KSAoYXBwIChhcHAgKGdsb2JhbCBpbnRfc3ViKSAoaW50IDE3KSkgKGludCA3KSkpIChhcHAgKGFwcCAoZ2xvYmFsIGludF9hZGQpIChpbnQgMikpIChpbnQgMTcpKSkjMTEz	pieces=type::(data Bool () ());;term::(app (app (global int_gt) (app (app (global int_sub) (int 17)) (int 7))) (app (app (global int_add) (int 2)) (int 17)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBWZWMgKCkgKCh2YXIgMCkpKXxjdHgxKGRhdGEgTmF0ICgpICgpKXx0eXBlKHR5cGUgMCl8dGVybShjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgVmVjICgpICgodmFyIDApKSkgKHR5cGUgMCkpKSAoYnJhbmNoIHZuaWwgMCAoZGF0YSBCZCAoKSAoKSkpIChicmFuY2ggdmNvbnMgMyAoZGF0YSBCZCAoKSAoKSkpKSMxMTQ=	pieces=ctx0::(data Vec () ((var 0)));;ctx1::(data Nat () ());;type::(type 0);;term::(case (var 0) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (type 0))) (branch vnil 0 (data Bd () ())) (branch vcons 3 (data Bd () ())))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBCZCAoKSAoKSkpICgoY3RvciBUKSAoY3RvciBUKSkpfHRlcm0oYXBwIChjYXNlIChjdG9yIHJlZmxleGl2ZSAoZGF0YSBCZCAoKSAoKSkgKGN0b3IgVCkpIChsYW0gKGRhdGEgQmQgKCkgKCkpIChsYW0gKGRhdGEgQmQgKCkgKCkpIChsYW0gKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgQmQgKCkgKCkpKSAoKHZhciAxKSAodmFyIDApKSkgKHBpIChhcHAgKGxhbSAoZGF0YSBCZCAoKSAoKSkgKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgQmQgKCkgKCkpKSAoKGN0b3IgVCkgKGN0b3IgVCkpKSkgKHZhciAyKSkgKGFwcCAobGFtIChkYXRhIEJkICgpICgpKSAoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBCZCAoKSAoKSkpICgoY3RvciBUKSAoY3RvciBUKSkpKSAodmFyIDIpKSkpKSkgKGJyYW5jaCByZWZsZXhpdmUgMSAobGFtIChhcHAgKGxhbSAoZGF0YSBCZCAoKSAoKSkgKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgQmQgKCkgKCkpKSAoKGN0b3IgVCkgKGN0b3IgVCkpKSkgKGN0b3IgVCkpICh2YXIgMCkpKSkgKGN0b3IgcmVmbGV4aXZlIChjdG9yIFQpKSkjMTE1	pieces=type::(data Equivalent ((data Bd () ())) ((ctor T) (ctor T)));;term::(app (case (ctor reflexive (data Bd () ()) (ctor T)) (lam (data Bd () ()) (lam (data Bd () ()) (lam (data Equivalent ((data Bd () ())) ((var 1) (var 0))) (pi (app (lam (data Bd () ()) (data Equivalent ((data Bd () ())) ((ctor T) (ctor T)))) (var 2)) (app (lam (data Bd () ()) (data Equivalent ((data Bd () ())) ((ctor T) (ctor T)))) (var 2)))))) (branch reflexive 1 (lam (app (lam (data Bd () ()) (data Equivalent ((data Bd () ())) ((ctor T) (ctor T)))) (ctor T)) (var 0)))) (ctor reflexive (ctor T)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQRtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnxjdHgwKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgTmF0ICgpICgpKSkgKChjYXNlICh2YXIgMSkgKGxhbSAoZGF0YSBCb29sICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIEZhbHNlIDAgKGN0b3IgWikpIChicmFuY2ggVHJ1ZSAwIChjdG9yIFopKSkgKGNhc2UgKHZhciAxKSAobGFtIChkYXRhIEJvb2wgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggRmFsc2UgMCAoY3RvciBaKSkgKGJyYW5jaCBUcnVlIDAgKGN0b3IgWikpKSkpfGN0eDEoZGF0YSBCb29sICgpICgpKXxjdHgyKGRhdGEgVmVjICgpICgodmFyIDApKSl8Y3R4MyhkYXRhIE5hdCAoKSAoKSl8dHlwZShkYXRhIE5hdCAoKSAoKSl8dGVybShjYXNlICh2YXIgMikgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgVmVjICgpICgodmFyIDApKSkgKGRhdGEgTmF0ICgpICgpKSkpIChicmFuY2ggdm5pbCAwIChjdG9yIFMgKGN0b3IgUyAoY3RvciBTIChjdG9yIFMgKGN0b3IgWikpKSkpKSAoYnJhbmNoIHZjb25zIDMgKGN0b3IgUyAoY3RvciBTIChjdG9yIFopKSkpKSMxMTY=	pieces=ctx0::(data Equivalent ((data Nat () ())) ((case (var 1) (lam (data Bool () ()) (data Nat () ())) (branch False 0 (ctor Z)) (branch True 0 (ctor Z))) (case (var 1) (lam (data Bool () ()) (data Nat () ())) (branch False 0 (ctor Z)) (branch True 0 (ctor Z)))));;ctx1::(data Bool () ());;ctx2::(data Vec () ((var 0)));;ctx3::(data Nat () ());;type::(data Nat () ());;term::(case (var 2) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (data Nat () ()))) (branch vnil 0 (ctor S (ctor S (ctor S (ctor S (ctor Z)))))) (branch vcons 3 (ctor S (ctor S (ctor Z)))))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X2x0KSAoaW50IC0xMCkpIChpbnQgLTkpKSMxMTc=	pieces=type::(data Bool () ());;term::(app (app (global int_lt) (int -10)) (int -9))
antigen-record	kind=serialize	assay=serialize/roundtrip	label=lossless	seed=-	note=serialization roundtrip (decode ∘ encode = id)	scaffold=-	key=c2VyaWFsaXplL3JvdW5kdHJpcHx0ZXJtKGNhc2UgKGFwcCAoY3RvciBaICh0eXBlIDApKSAodmFyIDIpKSAocGkgKGludCAtNCkgKGFwcCAoYXBwIChnbG9iYWwgaW50X2x0KSAobmF0IDEpKSAodHlwZSAwKSkpKSMxMTg=	pieces=term::(case (app (ctor Z (type 0)) (var 2)) (pi (int -4) (app (app (global int_lt) (nat 1)) (type 0))))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnxjdHgwKGRhdGEgVHkgKCkgKCh2YXIgMCkpKXxjdHgxKHR5cGUgMCl8dHlwZShkYXRhIE5hdCAoKSAoKSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSAodHlwZSAwKSAobGFtIChkYXRhIFR5ICgpICgodmFyIDApKSkgKGRhdGEgTmF0ICgpICgpKSkpIChicmFuY2ggdG5hdCAwIChjdG9yIFMgKGN0b3IgUyAoY3RvciBTIChjdG9yIFMgKGN0b3IgWikpKSkpKSAoYnJhbmNoIHRiZCAwIChjdG9yIFopKSAoYnJhbmNoIHRpbnQgMCAoY3RvciBaKSkgKGJyYW5jaCB0Zmx0IDAgKGN0b3IgWikpIChicmFuY2ggdHBpIDAgKGN0b3IgWikpIChicmFuY2ggdHNpZyAwIChjdG9yIFopKSAoYnJhbmNoIHR2ZWMgMCAoY3RvciBaKSkpIzExOQ==	pieces=ctx0::(data Ty () ((var 0)));;ctx1::(type 0);;type::(data Nat () ());;term::(case (var 0) (lam (type 0) (lam (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor S (ctor S (ctor S (ctor S (ctor Z)))))) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZmxvYXQtdHlwZSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2RpdikgKGZsb2F0IC0xLjApKSAoYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9hZGQpIChmbG9hdCAtMS43NSkpIChmbG9hdCAtMi43NSkpKSMxMjA=	pieces=type::(float-type);;term::(app (app (global float_div) (float -1.0)) (app (app (global float_add) (float -1.75)) (float -2.75)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGZsb2F0LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9zdWIpIChmbG9hdCAtNS4wKSkgKGZsb2F0IDQuMjUpKSMxMjE=	pieces=type::(float-type);;term::(app (app (global float_sub) (float -5.0)) (float 4.25))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBFcXVpdmFsZW50ICgoZmxvYXQtdHlwZSkpICgoZmxvYXQgMC41KSAoZmxvYXQgMC41KSkpfHRlcm0oYXBwIChjYXNlIChjdG9yIHJlZmxleGl2ZSAoZmxvYXQtdHlwZSkgKGZsb2F0IDAuNSkpIChsYW0gKGZsb2F0LXR5cGUpIChsYW0gKGZsb2F0LXR5cGUpIChsYW0gKGRhdGEgRXF1aXZhbGVudCAoKGZsb2F0LXR5cGUpKSAoKHZhciAxKSAodmFyIDApKSkgKHBpIChhcHAgKGxhbSAoZmxvYXQtdHlwZSkgKGRhdGEgRXF1aXZhbGVudCAoKGZsb2F0LXR5cGUpKSAoKGZsb2F0IDAuNSkgKGZsb2F0IDAuNSkpKSkgKHZhciAyKSkgKGFwcCAobGFtIChmbG9hdC10eXBlKSAoZGF0YSBFcXVpdmFsZW50ICgoZmxvYXQtdHlwZSkpICgoZmxvYXQgMC41KSAoZmxvYXQgMC41KSkpKSAodmFyIDIpKSkpKSkgKGJyYW5jaCByZWZsZXhpdmUgMSAobGFtIChhcHAgKGxhbSAoZmxvYXQtdHlwZSkgKGRhdGEgRXF1aXZhbGVudCAoKGZsb2F0LXR5cGUpKSAoKGZsb2F0IDAuNSkgKGZsb2F0IDAuNSkpKSkgKGZsb2F0IDAuNSkpICh2YXIgMCkpKSkgKGN0b3IgcmVmbGV4aXZlIChmbG9hdCAwLjUpKSkjMTIy	pieces=type::(data Equivalent ((float-type)) ((float 0.5) (float 0.5)));;term::(app (case (ctor reflexive (float-type) (float 0.5)) (lam (float-type) (lam (float-type) (lam (data Equivalent ((float-type)) ((var 1) (var 0))) (pi (app (lam (float-type) (data Equivalent ((float-type)) ((float 0.5) (float 0.5)))) (var 2)) (app (lam (float-type) (data Equivalent ((float-type)) ((float 0.5) (float 0.5)))) (var 2)))))) (branch reflexive 1 (lam (app (lam (float-type) (data Equivalent ((float-type)) ((float 0.5) (float 0.5)))) (float 0.5)) (var 0)))) (ctor reflexive (float 0.5)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBTcSAoKSAoKG5hdCA0KSAoY3RvciBTIChjdG9yIFopKSkpfHR5cGUoZGF0YSBOYXQgKCkgKCkpfHRlcm0oY2FzZSAodmFyIDApIChsYW0gKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBTcSAoKSAoKHZhciAyKSAodmFyIDEpKSkgKGRhdGEgTmF0ICgpICgpKSkpKSAoYnJhbmNoIG1rc3EgMSAoY3RvciBTIChjdG9yIFMgKGN0b3IgWikpKSkpIzEyMw==	pieces=ctx0::(data Sq () ((nat 4) (ctor S (ctor Z))));;type::(data Nat () ());;term::(case (var 0) (lam (data Nat () ()) (lam (data Nat () ()) (lam (data Sq () ((var 2) (var 1))) (data Nat () ())))) (branch mksq 1 (ctor S (ctor S (ctor Z)))))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2d0KSAoYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9tdWwpIChmbG9hdCAtNC4yNSkpIChmbG9hdCAtMC41KSkpIChmbG9hdCAyLjApKSMxMjQ=	pieces=type::(data Bool () ());;term::(app (app (global float_gt) (app (app (global float_mul) (float -4.25)) (float -0.5))) (float 2.0))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGludC10eXBlKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X3N1YikgKGFwcCAoYXBwIChnbG9iYWwgaW50X211bCkgKGludCA0KSkgKGludCAtOSkpKSAoaW50IDYpKSMxMjU=	pieces=type::(int-type);;term::(app (app (global int_sub) (app (app (global int_mul) (int 4)) (int -9))) (int 6))
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3xjdHgwKGRhdGEgVmVjICgpICgodmFyIDApKSl8Y3R4MShkYXRhIE5hdCAoKSAoKSl8dHlwZShpbnQtdHlwZSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgVmVjICgpICgodmFyIDApKSkgKGludC10eXBlKSkpIChicmFuY2ggdm5pbCAwIChpbnQgMCkpIChicmFuY2ggdmNvbnMgMyAoaW50IDUpKSkjMTI2	pieces=ctx0::(data Vec () ((var 0)));;ctx1::(data Nat () ());;type::(int-type);;term::(case (var 0) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (int-type))) (branch vnil 0 (int 0)) (branch vcons 3 (int 5)))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case motive returns a non-type var	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gKGRhdGEgTmF0ICgpICgpKSAodmFyIDApKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGN0b3IgWikpKSMxMjc=	pieces=term::(case (ctor Z) (lam (data Nat () ()) (var 0)) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBUZ2YgKCkgKChmbG9hdCAwLjApKSl8dHlwZShkYXRhIE5hdCAoKSAoKSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSAoZmxvYXQtdHlwZSkgKGxhbSAoZGF0YSBUZ2YgKCkgKCh2YXIgMCkpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKGJyYW5jaCB0Z2YwIDAgKGN0b3IgUyAoY3RvciBTIChjdG9yIFopKSkpIChicmFuY2ggdGdmMSAwIChjdG9yIFopKSkjMTI4	pieces=ctx0::(data Tgf () ((float 0.0)));;type::(data Nat () ());;term::(case (var 0) (lam (float-type) (lam (data Tgf () ((var 0))) (data Nat () ()))) (branch tgf0 0 (ctor S (ctor S (ctor Z)))) (branch tgf1 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9sZSkgKGludCAxMSkpIChpbnQgLTcpKSMxMjk=	pieces=type::(data Bool () ());;term::(app (app (global int_le) (int 11)) (int -7))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2xlKSAoYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9hZGQpIChmbG9hdCAxLjApKSAoZmxvYXQgMi43NSkpKSAoZmxvYXQgLTIuMjUpKSMxMzA=	pieces=type::(data Bool () ());;term::(app (app (global float_le) (app (app (global float_add) (float 1.0)) (float 2.75))) (float -2.25))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZmxvYXQtdHlwZSl8dGVybShhcHAgKGdsb2JhbCBmbG9hdF9uZWcpIChmbG9hdCAtNC41KSkjMTMx	pieces=type::(float-type);;term::(app (global float_neg) (float -4.5))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGludC10eXBlKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X3JlbSkgKGludCAxMCkpIChhcHAgKGFwcCAoZ2xvYmFsIGludF9hZGQpIChpbnQgMTQpKSAoYXBwIChhcHAgKGdsb2JhbCBpbnRfZGl2KSAoaW50IC0xMSkpIChpbnQgLTE5KSkpKSMxMzI=	pieces=type::(int-type);;term::(app (app (global int_rem) (int 10)) (app (app (global int_add) (int 14)) (app (app (global int_div) (int -11)) (int -19))))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGludC10eXBlKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X3N1YikgKGludCAtMTMpKSAoYXBwIChhcHAgKGdsb2JhbCBpbnRfZGl2KSAoaW50IDUpKSAoYXBwIChhcHAgKGdsb2JhbCBpbnRfcmVtKSAoaW50IDEwKSkgKGludCAxKSkpKSMxMzM=	pieces=type::(int-type);;term::(app (app (global int_sub) (int -13)) (app (app (global int_div) (int 5)) (app (app (global int_rem) (int 10)) (int 1))))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnxjdHgwKGRhdGEgVHkgKCkgKChkYXRhIFZlYyAoKGN0b3IgUyAoY3RvciBaKSkpICgpKSkpfHR5cGUoZGF0YSBOYXQgKCkgKCkpfHRlcm0oY2FzZSAodmFyIDApIChsYW0gKHR5cGUgMCkgKGxhbSAoZGF0YSBUeSAoKSAoKHZhciAwKSkpIChkYXRhIE5hdCAoKSAoKSkpKSAoYnJhbmNoIHRuYXQgMCAoY3RvciBTIChjdG9yIFMgKGN0b3IgWikpKSkgKGJyYW5jaCB0YmQgMCAoY3RvciBaKSkgKGJyYW5jaCB0aW50IDAgKGN0b3IgWikpIChicmFuY2ggdGZsdCAwIChjdG9yIFopKSAoYnJhbmNoIHRwaSAwIChjdG9yIFopKSAoYnJhbmNoIHRzaWcgMCAoY3RvciBaKSkgKGJyYW5jaCB0dmVjIDAgKGN0b3IgWikpKSMxMzQ=	pieces=ctx0::(data Ty () ((data Vec ((ctor S (ctor Z))) ())));;type::(data Nat () ());;term::(case (var 0) (lam (type 0) (lam (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor S (ctor S (ctor Z)))) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfbHQpIChmbG9hdCAtNC43NSkpIChmbG9hdCAwLjI1KSkjMTM1	pieces=type::(data Bool () ());;term::(app (app (global float_lt) (float -4.75)) (float 0.25))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2VxKSAoYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9hZGQpIChmbG9hdCAtMi4wKSkgKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfZGl2KSAoZmxvYXQgMy4yNSkpIChmbG9hdCAwLjApKSkpIChhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X211bCkgKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfYWRkKSAoZmxvYXQgLTIuNSkpIChmbG9hdCA0LjI1KSkpIChmbG9hdCAyLjUpKSkjMTM2	pieces=type::(data Bool () ());;term::(app (app (global float_eq) (app (app (global float_add) (float -2.0)) (app (app (global float_div) (float 3.25)) (float 0.0)))) (app (app (global float_mul) (app (app (global float_add) (float -2.5)) (float 4.25))) (float 2.5)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2dlKSAoZmxvYXQgMC43NSkpIChmbG9hdCAtNC4wKSkjMTM3	pieces=type::(data Bool () ());;term::(app (app (global float_ge) (float 0.75)) (float -4.0))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoaW50LXR5cGUpfHRlcm0oYXBwIChnbG9iYWwgaW50X25lZykgKGFwcCAoYXBwIChnbG9iYWwgaW50X3JlbSkgKGludCA2KSkgKGludCA0KSkpIzEzOA==	pieces=type::(int-type);;term::(app (global int_neg) (app (app (global int_rem) (int 6)) (int 4)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9nZSkgKGFwcCAoYXBwIChnbG9iYWwgaW50X3JlbSkgKGludCAtMTgpKSAoaW50IC02KSkpIChpbnQgNikpIzEzOQ==	pieces=type::(data Bool () ());;term::(app (app (global int_ge) (app (app (global int_rem) (int -18)) (int -6))) (int 6))
