antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_fields_only_ctor	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWaW5mZXJfZmllbGRzX29ubHlfY3Rvcg==	key=a2VybmVsL3Byb2JlfCMw	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: opaque_family_positivity	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYb3BhcXVlX2ZhbWlseV9wb3NpdGl2aXR5	key=a2VybmVsL3Byb2JlfCMx	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validate_cert_builtin_op	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYdmFsaWRhdGVfY2VydF9idWlsdGluX29w	key=a2VybmVsL3Byb2JlfCMy	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_out_of_range	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaY2hlY2tfYm91bmRlZF9vdXRfb2ZfcmFuZ2U=	key=a2VybmVsL3Byb2JlfCMz	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_absurd	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAMaW5mZXJfYWJzdXJk	key=a2VybmVsL3Byb2JlfCM0	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: positivity_through_ctor	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXcG9zaXRpdml0eV90aHJvdWdoX2N0b3I=	key=a2VybmVsL3Byb2JlfCM1	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: occurs_bare_global	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAASb2NjdXJzX2JhcmVfZ2xvYmFs	key=a2VybmVsL3Byb2JlfCM2	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: quote_value_surface	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATcXVvdGVfdmFsdWVfc3VyZmFjZQ==	key=a2VybmVsL3Byb2JlfCM3	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: quote_foreign_vdata	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATcXVvdGVfZm9yZWlnbl92ZGF0YQ==	key=a2VybmVsL3Byb2JlfCM4	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_nontuple_call_arg	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWY2VydF9ub250dXBsZV9jYWxsX2FyZw==	key=a2VybmVsL3Byb2JlfCM5	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: conv_bounded_crossrep	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAVY29udl9ib3VuZGVkX2Nyb3NzcmVw	key=a2VybmVsL3Byb2JlfCMxMA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_calls_nontuple_head	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYY2VydF9jYWxsc19ub250dXBsZV9oZWFk	key=a2VybmVsL3Byb2JlfCMxMQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_bounded_unregistered	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaaW5mZXJfYm91bmRlZF91bnJlZ2lzdGVyZWQ=	key=a2VybmVsL3Byb2JlfCMxMg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: serialize_special_atoms	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXc2VyaWFsaXplX3NwZWNpYWxfYXRvbXM=	key=a2VybmVsL3Byb2JlfCMxMw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: whnf_arity2_direct	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAASd2huZl9hcml0eTJfZGlyZWN0	key=a2VybmVsL3Byb2JlfCMxNA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_bounded_registered	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYaW5mZXJfYm91bmRlZF9yZWdpc3RlcmVk	key=a2VybmVsL3Byb2JlfCMxNQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_unknown_tuple_node	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXY2VydF91bmtub3duX3R1cGxlX25vZGU=	key=a2VybmVsL3Byb2JlfCMxNg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_bounded_peel	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARZXZhbF9ib3VuZGVkX3BlZWw=	key=a2VybmVsL3Byb2JlfCMxNw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: conv_unknown_ctor_fallback	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaY29udl91bmtub3duX2N0b3JfZmFsbGJhY2s=	key=a2VybmVsL3Byb2JlfCMxOA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: positivity_alias_expansion	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAacG9zaXRpdml0eV9hbGlhc19leHBhbnNpb24=	key=a2VybmVsL3Byb2JlfCMxOQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: sort_value_type_formers	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXc29ydF92YWx1ZV90eXBlX2Zvcm1lcnM=	key=a2VybmVsL3Byb2JlfCMyMA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: conv_no_delta_value_surface	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAbY29udl9ub19kZWx0YV92YWx1ZV9zdXJmYWNl	key=a2VybmVsL3Byb2JlfCMyMQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: apply_nonfun	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAMYXBwbHlfbm9uZnVu	key=a2VybmVsL3Byb2JlfCMyMg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: normalize_opts	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAObm9ybWFsaXplX29wdHM=	key=a2VybmVsL3Byb2JlfCMyMw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_def_unknown	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARY2hlY2tfZGVmX3Vua25vd24=	key=a2VybmVsL3Byb2JlfCMyNA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_not_concrete	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaY2hlY2tfYm91bmRlZF9ub3RfY29uY3JldGU=	key=a2VybmVsL3Byb2JlfCMyNQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_negative_debruijn	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWZXZhbF9uZWdhdGl2ZV9kZWJydWlqbg==	key=a2VybmVsL3Byb2JlfCMyNg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_bounded_no_branch	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWZXZhbF9ib3VuZGVkX25vX2JyYW5jaA==	key=a2VybmVsL3Byb2JlfCMyNw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: unify_rigid_value_heads	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXdW5pZnlfcmlnaWRfdmFsdWVfaGVhZHM=	key=a2VybmVsL3Byb2JlfCMyOA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_nontuple_list_elem	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXY2VydF9ub250dXBsZV9saXN0X2VsZW0=	key=a2VybmVsL3Byb2JlfCMyOQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validator_rejects_hole_body	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAbdmFsaWRhdG9yX3JlamVjdHNfaG9sZV9ib2R5	key=a2VybmVsL3Byb2JlfCMzMA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_in_range	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWY2hlY2tfYm91bmRlZF9pbl9yYW5nZQ==	key=a2VybmVsL3Byb2JlfCMzMQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: infer_value_type_formers	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYaW5mZXJfdmFsdWVfdHlwZV9mb3JtZXJz	key=a2VybmVsL3Byb2JlfCMzMg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_tower	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATY2hlY2tfYm91bmRlZF90b3dlcg==	key=a2VybmVsL3Byb2JlfCMzMw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: serialize_value_surface	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXc2VyaWFsaXplX3ZhbHVlX3N1cmZhY2U=	key=a2VybmVsL3Byb2JlfCMzNA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_no_branch	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAOZXZhbF9ub19icmFuY2g=	key=a2VybmVsL3Byb2JlfCMzNQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_bitwise_fold	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARZXZhbF9iaXR3aXNlX2ZvbGQ=	key=a2VybmVsL3Byb2JlfCMzNg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: unify_bounded_bridge	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAUdW5pZnlfYm91bmRlZF9icmlkZ2U=	key=a2VybmVsL3Byb2JlfCMzNw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: cert_dangling_callee	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAUY2VydF9kYW5nbGluZ19jYWxsZWU=	key=a2VybmVsL3Byb2JlfCMzOA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: decode_unknown_symbol	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAVZGVjb2RlX3Vua25vd25fc3ltYm9s	key=a2VybmVsL3Byb2JlfCMzOQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_ctor_via_infer	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAUY2hlY2tfY3Rvcl92aWFfaW5mZXI=	key=a2VybmVsL3Byb2JlfCM0MA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_ctor_arity	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAQY2hlY2tfY3Rvcl9hcml0eQ==	key=a2VybmVsL3Byb2JlfCM0MQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: conv_atom_binary	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAQY29udl9hdG9tX2JpbmFyeQ==	key=a2VybmVsL3Byb2JlfCM0Mg==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: serialize_malformed_symbol	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAac2VyaWFsaXplX21hbGZvcm1lZF9zeW1ib2w=	key=a2VybmVsL3Byb2JlfCM0Mw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: remap_index_passthrough	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAXcmVtYXBfaW5kZXhfcGFzc3Rocm91Z2g=	key=a2VybmVsL3Byb2JlfCM0NA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: check_bounded_wrong_family	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAaY2hlY2tfYm91bmRlZF93cm9uZ19mYW1pbHk=	key=a2VybmVsL3Byb2JlfCM0NQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_nondata_scrutinee	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAWZXZhbF9ub25kYXRhX3NjcnV0aW5lZQ==	key=a2VybmVsL3Byb2JlfCM0Ng==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_bounded_iota	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAARZXZhbF9ib3VuZGVkX2lvdGE=	key=a2VybmVsL3Byb2JlfCM0Nw==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: eval_value_literals	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATZXZhbF92YWx1ZV9saXRlcmFscw==	key=a2VybmVsL3Byb2JlfCM0OA==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: whnf_nested_fuel_restore	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAAYd2huZl9uZXN0ZWRfZnVlbF9yZXN0b3Jl	key=a2VybmVsL3Byb2JlfCM0OQ==	pieces=
antigen-record	kind=kernel_probe	assay=kernel/probe	label=probe	seed=-	note=kernel def-level probe: validator_warn_emit	scaffold=g3QAAAABbQAAAAVwcm9iZW0AAAATdmFsaWRhdG9yX3dhcm5fZW1pdA==	key=a2VybmVsL3Byb2JlfCM1MA==	pieces=
antigen-record	kind=family	assay=positivity	label=positive	seed=-	note=occurs?/2 coverage (packed): 6 arrow-domain shapes	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAACdAAAAAVtAAAACWFyZ19uYW1lc2wAAAADbQAAAANwcTBtAAAAA3BxMW0AAAADcHEyam0AAAAEbmFtZW0AAAADUEMwbQAAAApxdWFudGl0aWVzbAAAAANtAAAAB3ByZXNlbnRtAAAAB3ByZXNlbnRtAAAAB3ByZXNlbnRqbQAAAApyaWR4X2NvdW50YQBtAAAADHJwYXJhbV9jb3VudGEAdAAAAAVtAAAACWFyZ19uYW1lc2wAAAADbQAAAANwcTBtAAAAA3BxMW0AAAADcHEyam0AAAAEbmFtZW0AAAADUEMxbQAAAApxdWFudGl0aWVzbAAAAANtAAAAB3ByZXNlbnRtAAAAB3ByZXNlbnRtAAAAB3ByZXNlbnRqbQAAAApyaWR4X2NvdW50YQBtAAAADHJwYXJhbV9jb3VudGEAam0AAAAPZmFtX2luZGV4X25hbWVzam0AAAAJZmFtX2xldmVsYQBtAAAACGZhbV9uYW1lbQAAAARQZ2VubQAAAA9mYW1fcGFyYW1fbmFtZXNq	key=cG9zaXRpdml0eXxjdG9yOjA6YXJnOjAocGkgKGN0b3IgUyAoY3RvciBaKSkgKGRhdGEgTmF0ICgpICgpKSl8Y3RvcjowOmFyZzoxKHBpIChkYXRhIEVxdWl2YWxlbnQgKChkYXRhIE5hdCAoKSAoKSkpICgoY3RvciBaKSAoY3RvciBaKSkpIChpbnQtdHlwZSkpfGN0b3I6MDphcmc6MihwaSAoY3RvciByZWZsZXhpdmUgKGN0b3IgWikpIChkYXRhIE5hdCAoKSAoKSkpfGN0b3I6MTphcmc6MChwaSAoY2FzZSAoY3RvciByZWZsZXhpdmUgKGN0b3IgWikpIChjdG9yIFopIChicmFuY2ggcmVmbGV4aXZlIDEgKGN0b3IgWikpKSAoaW50LXR5cGUpKXxjdG9yOjE6YXJnOjEocGkgKGNhc2UgKGN0b3IgWikgKGN0b3IgWikgKGJyYW5jaCBQQzAgMCAoY3RvciBaKSkpIChkYXRhIE5hdCAoKSAoKSkpfGN0b3I6MTphcmc6MihwaSAoYXBwIChpbnQgMCkgKGludCAwKSkgKGludC10eXBlKSkjNTE=	pieces=ctor:0:arg:0::(pi (ctor S (ctor Z)) (data Nat () ()));;ctor:0:arg:1::(pi (data Equivalent ((data Nat () ())) ((ctor Z) (ctor Z))) (int-type));;ctor:0:arg:2::(pi (ctor reflexive (ctor Z)) (data Nat () ()));;ctor:1:arg:0::(pi (case (ctor reflexive (ctor Z)) (ctor Z) (branch reflexive 1 (ctor Z))) (int-type));;ctor:1:arg:1::(pi (case (ctor Z) (ctor Z) (branch PC0 0 (ctor Z))) (data Nat () ()));;ctor:1:arg:2::(pi (app (int 0) (int 0)) (int-type))
antigen-record	kind=def_group	assay=totality/diverging	label=diverging	seed=-	note=self-call arg is a projection → arg_relation :unknown	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAABbQAAAAFoam0AAAAFbmFtZXNsAAAAAW0AAAABaGo=	key=dG90YWxpdHkvZGl2ZXJnaW5nfHR5cGU6aChwaSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpfGJvZHk6aChsYW0gKGRhdGEgTmF0ICgpICgpKSAoY2FzZSAodmFyIDApIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGFwcCAoZ2xvYmFsIGgpIChjYXNlIChjdG9yIG1rX3BhaXIgKHZhciAxKSAodmFyIDEpKSAobGFtIChkYXRhIFNpZ21hICgoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggbWtfcGFpciAyICh2YXIgMSkpKSkpKSkjNTI=	pieces=type:h::(pi (data Nat () ()) (data Nat () ()));;body:h::(lam (data Nat () ()) (case (var 0) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (app (global h) (case (ctor mk_pair (var 1) (var 1)) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1)))))))
antigen-record	kind=def_group	assay=totality/terminating	label=terminating	seed=-	note=structural recursion with a rich call-free base branch	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAABbQAAAAFoam0AAAAFbmFtZXNsAAAAAW0AAAABaGo=	key=dG90YWxpdHkvdGVybWluYXRpbmd8dHlwZTpoKHBpIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSl8Ym9keTpoKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggWiAwIChjdG9yIG1rX3BhaXIgKGNhc2UgKHZhciAwKSAobGFtIChkYXRhIFNpZ21hICgoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggbWtfcGFpciAyICh2YXIgMSkpKSAoY3RvciBta19wYWlyIChjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBTaWdtYSAoKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIG1rX3BhaXIgMiAodmFyIDApKSkgKGN0b3IgbWtfcGFpciAoZGF0YSBFcXVpdmFsZW50ICgodmFyIDApKSAoKHZhciAwKSAodmFyIDApKSkgKGN0b3IgbWtfcGFpciAoY3RvciByZWZsZXhpdmUgKHZhciAwKSkgKGN0b3IgbWtfcGFpciAoYXBwIChjYXNlIChjdG9yIHJlZmxleGl2ZSAodmFyIDApKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKHZhciAwKSkgKGJyYW5jaCByZWZsZXhpdmUgMSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKHZhciAwKSkpKSAodmFyIDApKSAoY3RvciBta19wYWlyIChwaSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChjdG9yIG1rX3BhaXIgKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGFwcCAodmFyIDApICh2YXIgMCkpKSkpKSkpKSkgKGJyYW5jaCBTIDEgKGFwcCAoZ2xvYmFsIGgpICh2YXIgMCkpKSkpIzUz	pieces=type:h::(pi (data Nat () ()) (data Nat () ()));;body:h::(lam (data Nat () ()) (case (var 0) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor mk_pair (case (var 0) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1))) (ctor mk_pair (case (var 0) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 0))) (ctor mk_pair (data Equivalent ((var 0)) ((var 0) (var 0))) (ctor mk_pair (ctor reflexive (var 0)) (ctor mk_pair (app (case (ctor reflexive (var 0)) (lam (data Nat () ()) (var 0)) (branch reflexive 1 (lam (data Nat () ()) (var 0)))) (var 0)) (ctor mk_pair (pi (data Nat () ()) (data Nat () ())) (ctor mk_pair (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (app (var 0) (var 0)))))))))) (branch S 1 (app (global h) (var 0)))))
antigen-record	kind=def_group	assay=totality/diverging	label=diverging	seed=-	note=nullary mutual loop f = g, g = f (0×0 cross-function edges)	scaffold=g3QAAAACbQAAAAVmb2N1c2wAAAACbQAAAAFmbQAAAAFnam0AAAAFbmFtZXNsAAAAAm0AAAABZm0AAAABZ2o=	key=dG90YWxpdHkvZGl2ZXJnaW5nfHR5cGU6ZihkYXRhIE5hdCAoKSAoKSl8Ym9keTpmKGdsb2JhbCBnKXx0eXBlOmcoZGF0YSBOYXQgKCkgKCkpfGJvZHk6ZyhnbG9iYWwgZikjNTQ=	pieces=type:f::(data Nat () ());;body:f::(global g);;type:g::(data Nat () ());;body:g::(global f)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Nl nat_lit!=nat_lit fast path (unify_one 1003, distinct)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmxjbQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChuYXQgMykjNTU=	pieces=idx:0::(nat 3)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=Tg tg0 [1] — int-literal heads agree (undecided)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADdGcwbQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACVGdtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChpbnQgMSkjNTY=	pieces=idx:0::(int 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Foo MkFoo vs rigid Z index — genuine S/Z clash (S9 control)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFTWtGb29tAAAACGN0eF92YXJzYQJtAAAABWRuYW1lbQAAAANGb29tAAAAC3BhcmFtX2NvdW50YQE=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopfHBhcmFtOjAodmFyIDEpIzU3	pieces=idx:0::(ctor Z);;param:0::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=SpineU stuck plus-application spine element — unify_spine :undecided drop (1047)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADc3B1bQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAAGU3BpbmVVbQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKGN0b3IgWikpIzU4	pieces=idx:0::(ctor S (ctor Z))
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Sq mksq [var0,var1] — forced equation (Solution step)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtzcW0AAAAIY3R4X3ZhcnNhAm0AAAAFZG5hbWVtAAAAAlNxbQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8aWR4OjEodmFyIDEpIzU5	pieces=idx:0::(var 0);;idx:1::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Foo MkFoo over a free index — param in result-index spine is SOLVABLE (S9)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFTWtGb29tAAAACGN0eF92YXJzYQJtAAAABWRuYW1lbQAAAANGb29tAAAAC3BhcmFtX2NvdW50YQE=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8cGFyYW06MCh2YXIgMSkjNjA=	pieces=idx:0::(var 0);;param:0::(var 1)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Ty tnat [Type0] — rigid data/Type clash	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEdG5hdG0AAAAIY3R4X3ZhcnNhAG0AAAAFZG5hbWVtAAAAAlR5bQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh0eXBlIDApIzYx	pieces=idx:0::(type 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=Nl nat_lit result index vs ctor-tower scrutinee — peel nat_lit->ctor (unify_one 1005/1006)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmxjbQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpIzYy	pieces=idx:0::(ctor S (ctor S (ctor Z)))
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=bad_motive	seed=-	note=motive = an opaque outer variable — apply_motive_checked's :vneutral arm keeps applying (kernel.ex:634); the motive never becomes a well-typed Pi, so infer still rejects with :bad_motive	scaffold=g3QAAAABbQAAAAxtb3RpdmVfcHJvYmVtAAAAB25ldXRyYWw=	key=YnJhbmNodW5pZnkvdmVyZGljdHwjNjM=	pieces=
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Cyc4b interleaved crossing — union-find self-loop collapse (bind_index 1073)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAGbWtjeWMybQAAAAhjdHhfdmFyc2ECbQAAAAVkbmFtZW0AAAAFQ3ljNGJtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8aWR4OjEodmFyIDEpfGlkeDoyKHZhciAxKXxpZHg6Myh2YXIgMCkjNjQ=	pieces=idx:0::(var 0);;idx:1::(var 1);;idx:2::(var 1);;idx:3::(var 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=bad_motive	seed=-	note=motive = a concrete non-function value (a Nat type-value) — apply_motive_checked halts on the very first application, its catch-all arm (kernel.ex:635)	scaffold=g3QAAAABbQAAAAxtb3RpdmVfcHJvYmVtAAAABm5vbmZ1bg==	key=YnJhbmNodW5pZnkvdmVyZGljdHwjNjU=	pieces=
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=solved	seed=-	note=Cyc4 crossing — multi-key cycle collapse	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFbWtjeWNtAAAACGN0eF92YXJzYQJtAAAABWRuYW1lbQAAAARDeWM0bQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MCh2YXIgMCl8aWR4OjEodmFyIDEpfGlkeDoyKHZhciAxKXxpZHg6Myh2YXIgMCkjNjY=	pieces=idx:0::(var 0);;idx:1::(var 1);;idx:2::(var 1);;idx:3::(var 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Sq mksq [Z,S Z] — merge conflict	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtzcW0AAAAIY3R4X3ZhcnNhAG0AAAAFZG5hbWVtAAAAAlNxbQAAAAtwYXJhbV9jb3VudGEA	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopfGlkeDoxKGN0b3IgUyAoY3RvciBaKSkjNjc=	pieces=idx:0::(ctor Z);;idx:1::(ctor S (ctor Z))
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Cyc1 self-cycle — param buries into own successor, occurs-check (var_cycle? 1028/1038)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAFaWRjeWNtAAAACGN0eF92YXJzYQFtAAAABWRuYW1lbQAAAARDeWMxbQAAAAtwYXJhbV9jb3VudGEB	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFMgKHZhciAwKSl8cGFyYW06MCh2YXIgMCkjNjg=	pieces=idx:0::(ctor S (var 0));;param:0::(var 0)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=impossible	seed=-	note=Dboth nested :data result index (ps and is both non-empty) — subst_params :data recursion (953), rigid head clash	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAGbWtib3RobQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAAFRGJvdGhtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopIzY5	pieces=idx:0::(ctor Z)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=CaseIdx :case-headed result index — subst_params :case recursion (960/961)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtjaW0AAAAIY3R4X3ZhcnNhAG0AAAAFZG5hbWVtAAAAB0Nhc2VJZHhtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChjdG9yIFopIzcw	pieces=idx:0::(ctor Z)
antigen-record	kind=branch_unify	assay=branchunify/verdict	label=trivial	seed=-	note=Nl ctor-tower result index vs nat_lit scrutinee — peel ctor->nat_lit (unify_one 1008/1009)	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAADbmx0bQAAAAhjdHhfdmFyc2EAbQAAAAVkbmFtZW0AAAACTmxtAAAAC3BhcmFtX2NvdW50YQA=	key=YnJhbmNodW5pZnkvdmVyZGljdHxpZHg6MChuYXQgMSkjNzE=	pieces=idx:0::(nat 1)
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): transport body ill-typed (Nat motive, Bd body)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShhcHAgKGNhc2UgKGN0b3IgcmVmbGV4aXZlIChkYXRhIE5hdCAoKSAoKSkgKGN0b3IgWikpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBOYXQgKCkgKCkpKSAoKHZhciAxKSAodmFyIDApKSkgKHBpIChhcHAgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpICh2YXIgMikpIChhcHAgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpICh2YXIgMikpKSkpKSAoYnJhbmNoIHJlZmxleGl2ZSAxIChsYW0gKGFwcCAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGN0b3IgWikpICh2YXIgMCkpKSkgKGN0b3IgRikpIzcy	pieces=term::(app (case (ctor reflexive (data Nat () ()) (ctor Z)) (lam (data Nat () ()) (lam (data Nat () ()) (lam (data Equivalent ((data Nat () ())) ((var 1) (var 0))) (pi (app (lam (data Nat () ()) (data Nat () ())) (var 2)) (app (lam (data Nat () ()) (data Nat () ())) (var 2)))))) (branch reflexive 1 (lam (app (lam (data Nat () ()) (data Nat () ())) (ctor Z)) (var 0)))) (ctor F))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): unknown ctor	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjdG9yIG5vc3VjaGN0b3IpIzcz	pieces=term::(ctor nosuchctor)
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): unknown global	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShnbG9iYWwgbm9zdWNoZGVmKSM3NA==	pieces=term::(global nosuchdef)
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case scrutinee not data	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChmbG9hdCAtMC41KSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkpIzc1	pieces=term::(case (float -0.5) (lam (data Nat () ()) (data Nat () ())))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): unknown family	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShkYXRhIE5vU3VjaEZhbWlseSAoKSAoKSkjNzY=	pieces=term::(data NoSuchFamily () ())
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case with unknown-ctor branch	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGN0b3IgWikpIChicmFuY2ggbm9zdWNoY3RvciAwIChjdG9yIFopKSkjNzc=	pieces=term::(case (ctor Z) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)) (branch nosuchctor 0 (ctor Z)))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case motive returns an unknown family	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOb1N1Y2hGYW1pbHkgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGN0b3IgWikpKSM3OA==	pieces=term::(case (ctor Z) (lam (data Nat () ()) (data NoSuchFamily () ())) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=nvar vs napp head mismatch (146)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgMCl8dDIoYXBwICh2YXIgMSkgKHR5cGUgMCkpIzc5	pieces=t1::(var 0);;t2::(app (var 1) (type 0))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=S/Z tower vs compact-lit (91)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpfHQyKG5hdCAyKSM4MA==	pieces=t1::(ctor S (ctor S (ctor Z)));;t2::(nat 2)
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=case first vs second component, branch-body mismatch (150)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBTaWdtYSAoKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIG1rX3BhaXIgMiAodmFyIDEpKSl8dDIoY2FzZSAodmFyIDApIChsYW0gKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBta19wYWlyIDIgKHZhciAwKSkpIzgx	pieces=t1::(case (var 0) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1)));;t2::(case (var 0) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vtype (187)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAodHlwZSAwKSl8dDIoYXBwICh2YXIgMCkgKHR5cGUgMCkpIzgy	pieces=t1::(app (var 0) (type 0));;t2::(app (var 0) (type 0))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=η neutral-vs-λ (70,108)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgMCl8dDIobGFtICh0eXBlIDApIChhcHAgKHZhciAxKSAodmFyIDApKSkjODM=	pieces=t1::(var 0);;t2::(lam (type 0) (app (var 1) (var 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=compact-nat distinct literals (85)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShuYXQgMil8dDIobmF0IDMpIzg0	pieces=t1::(nat 2);;t2::(nat 3)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=compact-lit vs S/Z tower (88)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShuYXQgMSl8dDIoY3RvciBTIChjdG9yIFopKSM4NQ==	pieces=t1::(nat 1);;t2::(ctor S (ctor Z))
antigen-record	kind=conv_pair	assay=conv/decision	label=distinct	seed=-	note=λ-vs-non-λ (109)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwVmYWxzZQ==	key=Y29udi9kZWNpc2lvbnx0MShsYW0gKHR5cGUgMCkgKHZhciAxKSl8dDIodHlwZSAwKSM4Ng==	pieces=t1::(lam (type 0) (var 1));;t2::(type 0)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vfloat_type (190)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZmxvYXQtdHlwZSkpfHQyKGFwcCAodmFyIDApIChmbG9hdC10eXBlKSkjODc=	pieces=t1::(app (var 0) (float-type));;t2::(app (var 0) (float-type))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vλ fallback → conv_struct η (199)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAobGFtICh0eXBlIDApICh0eXBlIDApKSl8dDIoYXBwICh2YXIgMCkgKGxhbSAodHlwZSAwKSAodHlwZSAwKSkpIzg4	pieces=t1::(app (var 0) (lam (type 0) (type 0)));;t2::(app (var 0) (lam (type 0) (type 0)))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vint (189)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoaW50IC03KSl8dDIoYXBwICh2YXIgMCkgKGludCAtNykpIzg5	pieces=t1::(app (var 0) (int -7));;t2::(app (var 0) (int -7))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=out-of-ctx var → neutral (eval)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MSh2YXIgNSl8dDIodmFyIDUpIzkw	pieces=t1::(var 5);;t2::(var 5)
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vint_type (188)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoaW50LXR5cGUpKXx0MihhcHAgKHZhciAwKSAoaW50LXR5cGUpKSM5MQ==	pieces=t1::(app (var 0) (int-type));;t2::(app (var 0) (int-type))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vnat no-δ fast path (194)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAobmF0IDMpKXx0MihhcHAgKHZhciAwKSAobmF0IDMpKSM5Mg==	pieces=t1::(app (var 0) (nat 3));;t2::(app (var 0) (nat 3))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vdata (193)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZGF0YSBOYXQgKCkgKCkpKXx0MihhcHAgKHZhciAwKSAoZGF0YSBOYXQgKCkgKCkpKSM5Mw==	pieces=t1::(app (var 0) (data Nat () ()));;t2::(app (var 0) (data Nat () ()))
antigen-record	kind=conv_pair	assay=conv/decision	label=convertible	seed=-	note=app-arg vfloat (191)	scaffold=g3QAAAACbQAAAANjdHhhA20AAAAGZXhwZWN0dwR0cnVl	key=Y29udi9kZWNpc2lvbnx0MShhcHAgKHZhciAwKSAoZmxvYXQgMy4wKSl8dDIoYXBwICh2YXIgMCkgKGZsb2F0IDMuMCkpIzk0	pieces=t1::(app (var 0) (float 3.0));;t2::(app (var 0) (float 3.0))
antigen-record	kind=check_mode	assay=check/verdict	label=reject	seed=-	note=check nosuchctor : List Nat — checking-mode unknown constructor (unknown_ctor)	scaffold=g3QAAAABbQAAAAhjdHhfdmFyc2EA	key=Y2hlY2svdmVyZGljdHx0ZXJtKGN0b3Igbm9zdWNoY3Rvcil8dHlwZShkYXRhIExpc3QgKChkYXRhIE5hdCAoKSAoKSkpICgpKSM5NQ==	pieces=term::(ctor nosuchctor);;type::(data List ((data Nat () ())) ())
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :mode must be :whnf|:nf (rejects a valid :delta atom used as :mode)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncEbW9kZXcJY2VydGlmaWVkag==	key=ZGVsdGEvbmZ8Izk2	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=δ+ι: snd kpair → S Z (project second via ι-on-case)	scaffold=-	key=ZGVsdGEvbmZ8dGVybShjYXNlIChnbG9iYWwga3BhaXIpIChsYW0gKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBta19wYWlyIDIgKHZhciAwKSkpfGV4cGVjdGVkKGN0b3IgUyAoY3RvciBaKSkjOTc=	pieces=term::(case (global kpair) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 0)));;expected::(ctor S (ctor Z))
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=ncase/branch_miss (unfolded): donly (S Z) unfolds to a case with no S arm — reduce_unfolded freezes it, never crashes	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGdsb2JhbCBkb25seSkgKGN0b3IgUyAoY3RvciBaKSkpfGV4cGVjdGVkKGFwcCAoZ2xvYmFsIGRvbmx5KSAoY3RvciBTIChjdG9yIFopKSkjOTg=	pieces=term::(app (global donly) (ctor S (ctor Z)));;expected::(app (global donly) (ctor S (ctor Z)))
antigen-record	kind=delta_reduce	assay=delta/nf	label=fuel_probe	seed=-	note=fuel/exhausted: idnat^3 Z needs 3 δ-steps; a 2-step budget reports :fuel_exhausted, never a truncated wrong value	scaffold=g3QAAAACbQAAAARvcHRzbAAAAAFoAncEZnVlbGECam0AAAAEd2FudHcOZnVlbF9leGhhdXN0ZWQ=	key=ZGVsdGEvbmZ8dGVybShhcHAgKGdsb2JhbCBpZG5hdCkgKGFwcCAoZ2xvYmFsIGlkbmF0KSAoYXBwIChnbG9iYWwgaWRuYXQpIChjdG9yIFopKSkpfGV4cGVjdGVkKGN0b3IgWikjOTk=	pieces=term::(app (global idnat) (app (global idnat) (app (global idnat) (ctor Z))));;expected::(ctor Z)
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/struct_eq: struct_eq Int 3 4 → False (δ-fold via the audited literal table)	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoYXBwIChnbG9iYWwgc3RydWN0X2VxKSAoaW50LXR5cGUpKSAoaW50IDMpKSAoaW50IDQpKXxleHBlY3RlZChjdG9yIEZhbHNlKSMxMDA=	pieces=term::(app (app (app (global struct_eq) (int-type)) (int 3)) (int 4));;expected::(ctor False)
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/arity_stuck: struct_eq Int 5 (unsaturated, 2 of 3 args) stays neutral — never a bogus fold	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoZ2xvYmFsIHN0cnVjdF9lcSkgKGludC10eXBlKSkgKGludCA1KSl8ZXhwZWN0ZWQoYXBwIChhcHAgKGdsb2JhbCBzdHJ1Y3RfZXEpIChpbnQtdHlwZSkpIChpbnQgNSkpIzEwMQ==	pieces=term::(app (app (global struct_eq) (int-type)) (int 5));;expected::(app (app (global struct_eq) (int-type)) (int 5))
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=builtin/struct_ne: struct_ne Int 5 5 → False (δ-fold via the audited literal table)	scaffold=-	key=ZGVsdGEvbmZ8dGVybShhcHAgKGFwcCAoYXBwIChnbG9iYWwgc3RydWN0X25lKSAoaW50LXR5cGUpKSAoaW50IDUpKSAoaW50IDUpKXxleHBlY3RlZChjdG9yIEZhbHNlKSMxMDI=	pieces=term::(app (app (app (global struct_ne) (int-type)) (int 5)) (int 5));;expected::(ctor False)
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :delta must be :certified|:none (rejects a valid :mode atom used as :delta)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncFZGVsdGF3BHdobmZq	key=ZGVsdGEvbmZ8IzEwMw==	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :fuel must be a positive integer or :infinity (0 is rejected)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncEZnVlbGEAag==	key=ZGVsdGEvbmZ8IzEwNA==	pieces=
antigen-record	kind=delta_reduce	assay=delta/nf	label=reduces	seed=-	note=ncase/branch_miss (direct): case (idnat (S Z)) {Z->Z} has no S arm — unfold_certified_head freezes it, never crashes	scaffold=-	key=ZGVsdGEvbmZ8dGVybShjYXNlIChhcHAgKGdsb2JhbCBpZG5hdCkgKGN0b3IgUyAoY3RvciBaKSkpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSAoYnJhbmNoIFogMCAoY3RvciBaKSkpfGV4cGVjdGVkKGNhc2UgKGFwcCAoZ2xvYmFsIGlkbmF0KSAoY3RvciBTIChjdG9yIFopKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggWiAwIChjdG9yIFopKSkjMTA1	pieces=term::(case (app (global idnat) (ctor S (ctor Z))) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)));;expected::(case (app (global idnat) (ctor S (ctor Z))) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)))
antigen-record	kind=delta_reduce	assay=delta/nf	label=opts_reject	seed=-	note=opts/reject: :stuck_cases must be :preserve (any other value is rejected — MatchError, rescued and re-raised)	scaffold=g3QAAAABbQAAAARvcHRzbAAAAAFoAncLc3R1Y2tfY2FzZXN3BWZhbHNlag==	key=ZGVsdGEvbmZ8IzEwNg==	pieces=
antigen-record	kind=dot_forcing	assay=forcing/dot	label=reject	seed=-	note=Sq mksq {n=.(S Z)} vs forced Z — multi-index reject	scaffold=g3QAAAAEbQAAAAVjbmFtZW0AAAAEbWtzcW0AAAAIY3R4X3ZhcnNhAG0AAAAGZmFtaWx5bQAAAAJTcW0AAAAEbmFtZW0AAAABbg==	key=Zm9yY2luZy9kb3R8aWR4OjAoY3RvciBaKXxpZHg6MShjdG9yIFopfHdyaXR0ZW4oY3RvciBTIChjdG9yIFopKSMxMDc=	pieces=idx:0::(ctor Z);;idx:1::(ctor Z);;written::(ctor S (ctor Z))
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAADNSA2	key=c2VyaWFsaXplL2RlY29kZXwjMTA4	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAEImFiYw==	key=c2VyaWFsaXplL2RlY29kZXwjMTA5	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAEKGludA==	key=c2VyaWFsaXplL2RlY29kZXwjMTEw	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAALKGZsb2F0IDEuNSk=	key=c2VyaWFsaXplL2RlY29kZXwjMTEx	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAANKGhvbGUgImFcImIiKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTEy	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAHKGludCAwKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTEz	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAHKG5hdCAwKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTE0	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAARKGFwcCBmb28gKGludCA1KSk=	key=c2VyaWFsaXplL2RlY29kZXwjMTE1	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAA	key=c2VyaWFsaXplL2RlY29kZXwjMTE2	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAQKGN0b3IgRm9vICh6enopKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTE3	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAALKGJvdW5kZWQgMCk=	key=c2VyaWFsaXplL2RlY29kZXwjMTE4	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAtKGNhc2UgKHZhciAwKSAodHlwZSAwKSAoYnJhbmNoIFogLTMgKHZhciAwKSkp	key=c2VyaWFsaXplL2RlY29kZXwjMTE5	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAIKGFic3VyZCk=	key=c2VyaWFsaXplL2RlY29kZXwjMTIw	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAKKGludC10eXBlKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTIx	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAApKGNhc2UgKHZhciAwKSAodmFyIDApIChicmFuY2ggWiAwICh6enopKSk=	key=c2VyaWFsaXplL2RlY29kZXwjMTIy	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAIKHR5cGUgMCk=	key=c2VyaWFsaXplL2RlY29kZXwjMTIz	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=valid_sexp	seed=-	note=decode probe (valid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAANKGhvbGUgImFcXGIiKQ==	key=c2VyaWFsaXplL2RlY29kZXwjMTI0	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAACKSk=	key=c2VyaWFsaXplL2RlY29kZXwjMTI1	pieces=
antigen-record	kind=decode_probe	assay=serialize/decode	label=invalid_sexp	seed=-	note=decode probe (invalid_sexp)	scaffold=g3QAAAABbQAAAAVpbnB1dG0AAAAaKGNhc2UgKHZhciAwKSAodmFyIDApIGZvbyk=	key=c2VyaWFsaXplL2RlY29kZXwjMTI2	pieces=
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=type former	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3x0eXBlKHR5cGUgMCl8dGVybShkYXRhIFNpZ21hICgoZmxvYXQtdHlwZSkgKGxhbSAoZmxvYXQtdHlwZSkgKGZsb2F0LXR5cGUpKSkgKCkpIzEyNw==	pieces=type::(type 0);;term::(data Sigma ((float-type) (lam (float-type) (float-type))) ())
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=parameterized wrong result-param arity	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAACcGNtAAAACnF1YW50aXRpZXNsAAAAAW0AAAAEbWFueWptAAAACnJpZHhfY291bnRhAW0AAAAMcnBhcmFtX2NvdW50YQBqbQAAAA9mYW1faW5kZXhfbmFtZXNsAAAAAW0AAAABbmptAAAACWZhbV9sZXZlbGEAbQAAAAhmYW1fbmFtZW0AAAABUG0AAAAPZmFtX3BhcmFtX25hbWVzbAAAAAFtAAAAAWFq	key=dW5pdmVyc2VzfGZhbV9wYXJhbTowKHR5cGUgMCl8ZmFtX2luZGV4OjAoaW50LXR5cGUpfGN0b3I6MDphcmc6MCh2YXIgMCl8Y3RvcjowOnJpZHg6MChpbnQgLTIpIzEyOA==	pieces=fam_param:0::(type 0);;fam_index:0::(int-type);;ctor:0:arg:0::(var 0);;ctor:0:ridx:0::(int -2)
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=parameterized non-uniform (result param = x)	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAACcGNtAAAACnF1YW50aXRpZXNsAAAAAW0AAAAEbWFueWptAAAACnJpZHhfY291bnRhAW0AAAAMcnBhcmFtX2NvdW50YQFqbQAAAA9mYW1faW5kZXhfbmFtZXNsAAAAAW0AAAABbmptAAAACWZhbV9sZXZlbGEAbQAAAAhmYW1fbmFtZW0AAAABUG0AAAAPZmFtX3BhcmFtX25hbWVzbAAAAAFtAAAAAWFq	key=dW5pdmVyc2VzfGZhbV9wYXJhbTowKHR5cGUgMCl8ZmFtX2luZGV4OjAoZmxvYXQtdHlwZSl8Y3RvcjowOmFyZzowKHZhciAwKXxjdG9yOjA6cmlkeDowKGZsb2F0IC00LjUpfGN0b3I6MDpycGFyYW06MCh2YXIgMCkjMTI5	pieces=fam_param:0::(type 0);;fam_index:0::(float-type);;ctor:0:arg:0::(var 0);;ctor:0:ridx:0::(float -4.5);;ctor:0:rparam:0::(var 0)
antigen-record	kind=family	assay=universes	label=ill_typed	seed=-	note=arg-bearing ctor with non-type field	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAABbQAAAAF4am0AAAAEbmFtZW0AAAADbWtpbQAAAApxdWFudGl0aWVzbAAAAAFtAAAAB3ByZXNlbnRqbQAAAApyaWR4X2NvdW50YQFtAAAADHJwYXJhbV9jb3VudGEAam0AAAAPZmFtX2luZGV4X25hbWVzbAAAAAFtAAAAAW5qbQAAAAlmYW1fbGV2ZWxhAG0AAAAIZmFtX25hbWVtAAAABElkeEltAAAAD2ZhbV9wYXJhbV9uYW1lc2o=	key=dW5pdmVyc2VzfGZhbV9pbmRleDowKGZsb2F0LXR5cGUpfGN0b3I6MDphcmc6MChmbG9hdCAwLjApfGN0b3I6MDpyaWR4OjAoZmxvYXQgLTEuNSkjMTMw	pieces=fam_index:0::(float-type);;ctor:0:arg:0::(float 0.0);;ctor:0:ridx:0::(float -1.5)
antigen-record	kind=elab_program	assay=elab/metamorphic	label=none	seed=-	note=computed_idx/rebuild invariant under alpha_rename	scaffold=g3QAAAAEbQAAAAhiYXNlX3NyY20AAAGSbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNMaXN0ID0gU05pbCB8IFNDb25zKE5hdCwgU0xpc3QpCiAgZm4gYXBwKHhzOiBTTGlzdCwgeXM6IFNMaXN0KSAtPiBTTGlzdCA9IG1hdGNoIHhzCiAgICBTTmlsKCkgLT4geXMKICAgIFNDb25zKGgsIHQpIC0+IFNDb25zKGgsIGFwcCh0LCB5cykpCiAgdHlwZSBGIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGxlYWYgOiBGKFNOaWwoKSkKICAgIG1rIDogRihhcykgLT4gRihicykgLT4gRihhcHAoYXMsIGJzKSkKICBmbiBnKHtwOiBTTGlzdH0sIHtxOiBTTGlzdH0sIHY6IEYoYXBwKHAsIHEpKSkgLT4gRihhcHAocCwgcSkpID0KICAgIG1hdGNoIHYKICAgICAgbGVhZigpIC0+IGxlYWYoKQogICAgICBtayhsLCByKSAtPiBtayhsLCByKQplbmQKbQAAAAJpZG0AAAAUY29tcHV0ZWRfaWR4L3JlYnVpbGRtAAAACXRyYW5zZm9ybW0AAAAMYWxwaGFfcmVuYW1lbQAAAAt2YXJpYW50X3NyY20AAAGWbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNMaXN0ID0gU05pbCB8IFNDb25zKE5hdCwgU0xpc3QpCiAgZm4gYXBwKHhzOiBTTGlzdCwgeXM6IFNMaXN0KSAtPiBTTGlzdCA9IG1hdGNoIHhzCiAgICBTTmlsKCkgLT4geXMKICAgIFNDb25zKGgsIHQpIC0+IFNDb25zKGgsIGFwcCh0LCB5cykpCiAgdHlwZSBGIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGxlYWYgOiBGKFNOaWwoKSkKICAgIG1rIDogRihhcykgLT4gRihicykgLT4gRihhcHAoYXMsIGJzKSkKICBmbiBnKHtwOiBTTGlzdH0sIHtxOiBTTGlzdH0sIHZ2MDogRihhcHAocCwgcSkpKSAtPiBGKGFwcChwLCBxKSkgPQogICAgbWF0Y2ggdnYwCiAgICAgIGxlYWYoKSAtPiBsZWFmKCkKICAgICAgbWsobCwgcikgLT4gbWsobCwgcikKZW5kCg==	key=ZWxhYi9tZXRhbW9ycGhpY3wjMTMx	pieces=
antigen-record	kind=elab_program	assay=elab/completeness	label=well_typed	seed=-	note=goal Equivalent(NV(n), v, v), reflexive(v)	scaffold=g3QAAAACbQAAAAJpZG0AAAAXZXFfdmFsdWUvdmFyL3JlZmxfc2NydXRtAAAAA3NyY20AAAHUbW9kIFAKICB0eXBlIE5hdCA9IFogfCBTKE5hdCkKICB0eXBlIFNOYXQgaW5kaWNlcyAobjogTmF0KQogICAgc3plcm8gOiBTTmF0KFopCiAgICBzc3VjIDogU05hdChuKSAtPiBTTmF0KFMobikpCiAgdHlwZSBOViBpbmRpY2VzIChuOiBOYXQpCiAgICB2eiA6IE5WKFopCiAgICB2cyA6IFNOYXQobikgLT4gTlYoUyhuKSkKICBmbiB0b1MobTogTmF0KSAtPiBTTmF0KG0pID0gbWF0Y2ggbQogICAgWigpIC0+IHN6ZXJvKCkKICAgIFMoaikgLT4gc3N1Yyh0b1MoaikpCiAgZm4gdmlldyhuOiBOYXQpIC0+IE5WKG4pID0gbWF0Y2ggbgogICAgWigpIC0+IHZ6KCkKICAgIFMobSkgLT4gdnModG9TKG0pKQogIGZuIGYoe246IE5hdH0sIHY6IE5WKG4pKSAtPiBFcXVpdmFsZW50KE5WKG4pLCB2LCB2KSA9CiAgICBtYXRjaCB2CiAgICAgIHZ6KCkgLT4gcmVmbGV4aXZlKHYpCiAgICAgIHZzKHMpIC0+IHJlZmxleGl2ZSh2KQplbmQK	key=ZWxhYi9jb21wbGV0ZW5lc3N8IzEzMg==	pieces=
antigen-record	kind=elab_program	assay=elab/dot_forcing	label=accept	seed=-	note=right dot on the plain dispatch path (landed C-b shape)	scaffold=g3QAAAADbQAAAAZleHBlY3R3BmFjY2VwdG0AAAACaWRtAAAAEmZvcmNlZC9wbGFpbi9yaWdodG0AAAADc3JjbQAAASttb2QgUAogIHR5cGUgTmF0ID0gWiB8IFMoTmF0KQogIHR5cGUgVmVjKGE6IFR5cGUpIGluZGljZXMgKG46IE5hdCkKICAgIHZuaWwgOiBWZWMoYSwgWikKICAgIHZjb25zIDogYSAtPiBWZWMoYSwgbikgLT4gVmVjKGEsIFMobikpCiAgdHlwZSBQYWNrKGE6IFR5cGUpIGluZGljZXMgKCkKICAgIHBrIDogVmVjKGEsIG0pIC0+IFBhY2soYSkKICBmbiBmKHthOiBUeXBlfSwge2s6IE5hdH0sIHY6IFZlYyhhLCBTKGspKSkgLT4gVmVjKGEsIFMoaykpID0gbWF0Y2ggdgogICAgdmNvbnMoe24gPSAua30sIGgsIHQpIC0+IHYKZW5kCg==	key=ZWxhYi9kb3RfZm9yY2luZ3wjMTMz	pieces=
antigen-record	kind=elab_program	assay=elab/dot_forcing	label=accept	seed=-	note=right dot on the carried-eq path (over-rejection guard)	scaffold=g3QAAAADbQAAAAZleHBlY3R3BmFjY2VwdG0AAAACaWRtAAAAFGZvcmNlZC9jYXJyaWVkL3JpZ2h0bQAAAANzcmNtAAABpG1vZCBQCiAgdHlwZSBOYXQgPSBaIHwgUyhOYXQpCiAgdHlwZSBTTGlzdCA9IFNOaWwgfCBTQ29ucyhOYXQsIFNMaXN0KQogIGZuIGFwcCh4czogU0xpc3QsIHlzOiBTTGlzdCkgLT4gU0xpc3QgPSBtYXRjaCB4cwogICAgU05pbCgpIC0+IHlzCiAgICBTQ29ucyhoLCB0KSAtPiBTQ29ucyhoLCBhcHAodCwgeXMpKQogIHR5cGUgSCBpbmRpY2VzIChuOiBOYXQsIHhzOiBTTGlzdCkKICAgIGhtayA6IEgoUyhtKSwgYXBwKGFzLCBicykpCiAgdHlwZSBHIGluZGljZXMgKHhzOiBTTGlzdCkKICAgIGd3cmFwIDogRyhjcykKICBmbiBnKHtqOiBOYXR9LCB7cDogU0xpc3R9LCB7cTogU0xpc3R9LCB2OiBIKFMoaiksIGFwcChwLCBxKSksIHc6IEcoYXBwKHAsIHEpKSkgLT4gTmF0ID0gbWF0Y2ggdgogICAgaG1rKHttID0gLmp9KSAtPiBaKCkKZW5kCg==	key=ZWxhYi9kb3RfZm9yY2luZ3wjMTM0	pieces=
antigen-record	kind=elab_program	assay=elab/soundness	label=well_typed	seed=-	note=boolean literal in inference position — Kernel.bool_type_value/1	scaffold=g3QAAAACbQAAAAJpZG0AAAAVbGl0X3R5cGluZy9ib29sX2luZmVybQAAAANzcmNtAAAAJW1vZCBQCiAgZm4gZmxhZygpIC0+IEJvb2wgPSB0cnVlCmVuZAo=	key=ZWxhYi9zb3VuZG5lc3N8IzEzNQ==	pieces=
antigen-record	kind=family	assay=inductive/env_roundtrip	label=well_typed	seed=-	note=Env-accessor roundtrip probe (AntigenEnv/antigenA, n=0)	scaffold=g3QAAAAFbQAAAAVjdG9yc2wAAAABdAAAAAVtAAAACWFyZ19uYW1lc2wAAAACbQAAAAF4bQAAAAF5am0AAAAEbmFtZW0AAAAIYW50aWdlbkFtAAAACnF1YW50aXRpZXNsAAAAAm0AAAAGZXJhc2VkbQAAAAdwcmVzZW50am0AAAAKcmlkeF9jb3VudGEBbQAAAAxycGFyYW1fY291bnRhAWptAAAAD2ZhbV9pbmRleF9uYW1lc2wAAAABbQAAAAFuam0AAAAJZmFtX2xldmVsYQBtAAAACGZhbV9uYW1lbQAAAApBbnRpZ2VuRW52bQAAAA9mYW1fcGFyYW1fbmFtZXNsAAAAAW0AAAABYWo=	key=aW5kdWN0aXZlL2Vudl9yb3VuZHRyaXB8ZmFtX3BhcmFtOjAodHlwZSAwKXxmYW1faW5kZXg6MChpbnQtdHlwZSl8Y3RvcjowOmFyZzowKHZhciAwKXxjdG9yOjA6YXJnOjEodmFyIDEpfGN0b3I6MDpyaWR4OjAoaW50IDApfGN0b3I6MDpycGFyYW06MCh2YXIgMikjMTM2	pieces=fam_param:0::(type 0);;fam_index:0::(int-type);;ctor:0:arg:0::(var 0);;ctor:0:arg:1::(var 1);;ctor:0:ridx:0::(int 0);;ctor:0:rparam:0::(var 2)
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X2VxKSAoaW50IDE3KSkgKGludCAxKSkjMTM3	pieces=type::(data Bool () ());;term::(app (app (global int_eq) (int 17)) (int 1))
antigen-record	kind=serialize	assay=serialize/roundtrip	label=lossless	seed=-	note=serialization roundtrip (decode ∘ encode = id)	scaffold=-	key=c2VyaWFsaXplL3JvdW5kdHJpcHx0ZXJtKHBpIChjYXNlICh0eXBlIDEpIChsYW0gKGdsb2JhbCBwbHVzKSAobmF0IDgpKSAoYnJhbmNoIFogMSAoZmxvYXQgMS41KSkgKGJyYW5jaCBaIDIgKGZsb2F0LXR5cGUpKSkgKGludC10eXBlKSkjMTM4	pieces=term::(pi (case (type 1) (lam (global plus) (nat 8)) (branch Z 1 (float 1.5)) (branch Z 2 (float-type))) (int-type))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGZsb2F0LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9hZGQpIChhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X211bCkgKGZsb2F0IC01LjApKSAoZmxvYXQgMS43NSkpKSAoZmxvYXQgLTEuMjUpKSMxMzk=	pieces=type::(float-type);;term::(app (app (global float_add) (app (app (global float_mul) (float -5.0)) (float 1.75))) (float -1.25))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBCb29sICgpICgpKSkgKChjdG9yIEZhbHNlKSAoY3RvciBGYWxzZSkpKXx0ZXJtKGFwcCAobGFtIChkYXRhIEVxdWl2YWxlbnQgKChkYXRhIEJvb2wgKCkgKCkpKSAoKGN0b3IgRmFsc2UpIChjdG9yIEZhbHNlKSkpICh2YXIgMCkpIChjdG9yIHJlZmxleGl2ZSAoZGF0YSBCb29sICgpICgpKSAoY3RvciBGYWxzZSkpKSMxNDA=	pieces=type::(data Equivalent ((data Bool () ())) ((ctor False) (ctor False)));;term::(app (lam (data Equivalent ((data Bool () ())) ((ctor False) (ctor False))) (var 0)) (ctor reflexive (data Bool () ()) (ctor False)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZmxvYXQtdHlwZSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2RpdikgKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfYWRkKSAoZmxvYXQgMS43NSkpIChhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X211bCkgKGZsb2F0IC0yLjc1KSkgKGZsb2F0IDEuMCkpKSkgKGZsb2F0IDAuMCkpIzE0MQ==	pieces=type::(float-type);;term::(app (app (global float_div) (app (app (global float_add) (float 1.75)) (app (app (global float_mul) (float -2.75)) (float 1.0)))) (float 0.0))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgQm9vbCAoKSAoKSkpICgoY3RvciBGYWxzZSkgKGN0b3IgRmFsc2UpKSl8dGVybShhcHAgKGNhc2UgKGN0b3IgcmVmbGV4aXZlIChkYXRhIEJvb2wgKCkgKCkpIChjdG9yIEZhbHNlKSkgKGxhbSAoZGF0YSBCb29sICgpICgpKSAobGFtIChkYXRhIEJvb2wgKCkgKCkpIChsYW0gKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgQm9vbCAoKSAoKSkpICgodmFyIDEpICh2YXIgMCkpKSAocGkgKGFwcCAobGFtIChkYXRhIEJvb2wgKCkgKCkpIChkYXRhIEVxdWl2YWxlbnQgKChkYXRhIEJvb2wgKCkgKCkpKSAoKGN0b3IgRmFsc2UpIChjdG9yIEZhbHNlKSkpKSAodmFyIDIpKSAoYXBwIChsYW0gKGRhdGEgQm9vbCAoKSAoKSkgKGRhdGEgRXF1aXZhbGVudCAoKGRhdGEgQm9vbCAoKSAoKSkpICgoY3RvciBGYWxzZSkgKGN0b3IgRmFsc2UpKSkpICh2YXIgMikpKSkpKSAoYnJhbmNoIHJlZmxleGl2ZSAxIChsYW0gKGFwcCAobGFtIChkYXRhIEJvb2wgKCkgKCkpIChkYXRhIEVxdWl2YWxlbnQgKChkYXRhIEJvb2wgKCkgKCkpKSAoKGN0b3IgRmFsc2UpIChjdG9yIEZhbHNlKSkpKSAoY3RvciBGYWxzZSkpICh2YXIgMCkpKSkgKGN0b3IgcmVmbGV4aXZlIChjdG9yIEZhbHNlKSkpIzE0Mg==	pieces=type::(data Equivalent ((data Bool () ())) ((ctor False) (ctor False)));;term::(app (case (ctor reflexive (data Bool () ()) (ctor False)) (lam (data Bool () ()) (lam (data Bool () ()) (lam (data Equivalent ((data Bool () ())) ((var 1) (var 0))) (pi (app (lam (data Bool () ()) (data Equivalent ((data Bool () ())) ((ctor False) (ctor False)))) (var 2)) (app (lam (data Bool () ()) (data Equivalent ((data Bool () ())) ((ctor False) (ctor False)))) (var 2)))))) (branch reflexive 1 (lam (app (lam (data Bool () ()) (data Equivalent ((data Bool () ())) ((ctor False) (ctor False)))) (ctor False)) (var 0)))) (ctor reflexive (ctor False)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2dlKSAoZmxvYXQgMy41KSkgKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfbXVsKSAoZmxvYXQgMi4wKSkgKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfc3ViKSAoZmxvYXQgMi4wKSkgKGZsb2F0IDAuNSkpKSkjMTQz	pieces=type::(data Bool () ());;term::(app (app (global float_ge) (float 3.5)) (app (app (global float_mul) (float 2.0)) (app (app (global float_sub) (float 2.0)) (float 0.5))))
antigen-record	kind=malformed	assay=term/rejection	label=ill_typed	seed=-	note=malformed (must reject): case motive returns a non-type var	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9yZWplY3Rpb258dGVybShjYXNlIChjdG9yIFopIChsYW0gKGRhdGEgTmF0ICgpICgpKSAodmFyIDApKSAoYnJhbmNoIFogMCAoY3RvciBaKSkgKGJyYW5jaCBTIDEgKGN0b3IgWikpKSMxNDQ=	pieces=term::(case (ctor Z) (lam (data Nat () ()) (var 0)) (branch Z 0 (ctor Z)) (branch S 1 (ctor Z)))
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=propositional equality (inductive Equivalent)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3x0eXBlKGRhdGEgRXF1aXZhbGVudCAoKGZsb2F0LXR5cGUpKSAoKGZsb2F0IDEuMCkgKGZsb2F0IDEuMCkpKXx0ZXJtKGFwcCAobGFtIChkYXRhIEVxdWl2YWxlbnQgKChmbG9hdC10eXBlKSkgKChmbG9hdCAxLjApIChmbG9hdCAxLjApKSkgKHZhciAwKSkgKGN0b3IgcmVmbGV4aXZlIChmbG9hdC10eXBlKSAoZmxvYXQgMS4wKSkpIzE0NQ==	pieces=type::(data Equivalent ((float-type)) ((float 1.0) (float 1.0)));;term::(app (lam (data Equivalent ((float-type)) ((float 1.0) (float 1.0))) (var 0)) (ctor reflexive (float-type) (float 1.0)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQRtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBFcXVpdmFsZW50ICgoZGF0YSBOYXQgKCkgKCkpKSAoKGNhc2UgKHZhciAxKSAobGFtIChkYXRhIFNpZ21hICgoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKCkpIChkYXRhIE5hdCAoKSAoKSkpIChicmFuY2ggbWtfcGFpciAyICh2YXIgMSkpKSAoY2FzZSAodmFyIDEpIChsYW0gKGRhdGEgU2lnbWEgKChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChkYXRhIE5hdCAoKSAoKSkpKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBta19wYWlyIDIgKHZhciAxKSkpKSl8Y3R4MShkYXRhIFNpZ21hICgoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgTmF0ICgpICgpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKCkpfGN0eDIoZGF0YSBWZWMgKCkgKCh2YXIgMCkpKXxjdHgzKGRhdGEgTmF0ICgpICgpKXx0eXBlKGRhdGEgTmF0ICgpICgpKXx0ZXJtKGNhc2UgKHZhciAyKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBWZWMgKCkgKCh2YXIgMCkpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKGJyYW5jaCB2bmlsIDAgKGN0b3IgUyAoY3RvciBTIChjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpKSkpIChicmFuY2ggdmNvbnMgMyAoY3RvciBTIChjdG9yIFMgKGN0b3IgUyAoY3RvciBaKSkpKSkpIzE0Ng==	pieces=ctx0::(data Equivalent ((data Nat () ())) ((case (var 1) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1))) (case (var 1) (lam (data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ()) (data Nat () ())) (branch mk_pair 2 (var 1)))));;ctx1::(data Sigma ((data Nat () ()) (lam (data Nat () ()) (data Nat () ()))) ());;ctx2::(data Vec () ((var 0)));;ctx3::(data Nat () ());;type::(data Nat () ());;term::(case (var 2) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (data Nat () ()))) (branch vnil 0 (ctor S (ctor S (ctor S (ctor S (ctor Z)))))) (branch vcons 3 (ctor S (ctor S (ctor S (ctor Z))))))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoaW50LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBpbnRfYWRkKSAoaW50IDIwKSkgKGludCAxNCkpIzE0Nw==	pieces=type::(int-type);;term::(app (app (global int_add) (int 20)) (int 14))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoaW50LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBpbnRfc3ViKSAoaW50IDE0KSkgKGludCA4KSkjMTQ4	pieces=type::(int-type);;term::(app (app (global int_sub) (int 14)) (int 8))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2x0KSAoZmxvYXQgLTQuMCkpIChhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X211bCkgKGFwcCAoZ2xvYmFsIGZsb2F0X25lZykgKGZsb2F0IDAuMCkpKSAoYXBwIChhcHAgKGdsb2JhbCBmbG9hdF9zdWIpIChmbG9hdCAtMi4yNSkpIChmbG9hdCAxLjUpKSkpIzE0OQ==	pieces=type::(data Bool () ());;term::(app (app (global float_lt) (float -4.0)) (app (app (global float_mul) (app (global float_neg) (float 0.0))) (app (app (global float_sub) (float -2.25)) (float 1.5))))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2xlKSAoZmxvYXQgLTQuMjUpKSAoZmxvYXQgNC41KSkjMTUw	pieces=type::(data Bool () ());;term::(app (app (global float_le) (float -4.25)) (float 4.5))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoYXBwIChnbG9iYWwgc3RydWN0X25lKSAoZmxvYXQtdHlwZSkpIChmbG9hdCAzLjc1KSkgKGZsb2F0IDQuMjUpKSMxNTE=	pieces=type::(data Bool () ());;term::(app (app (app (global struct_ne) (float-type)) (float 3.75)) (float 4.25))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X2d0KSAoaW50IC0yKSkgKGludCA4KSkjMTUy	pieces=type::(data Bool () ());;term::(app (app (global int_gt) (int -2)) (int 8))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoaW50LXR5cGUpfHRlcm0oYXBwIChnbG9iYWwgaW50X25lZykgKGFwcCAoYXBwIChnbG9iYWwgaW50X211bCkgKGludCAtNCkpIChpbnQgLTUpKSkjMTUz	pieces=type::(int-type);;term::(app (global int_neg) (app (app (global int_mul) (int -4)) (int -5)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGludC10eXBlKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X2RpdikgKGFwcCAoYXBwIChnbG9iYWwgaW50X2FkZCkgKGFwcCAoZ2xvYmFsIGludF9uZWcpIChpbnQgOCkpKSAoYXBwIChhcHAgKGdsb2JhbCBpbnRfbXVsKSAoaW50IC0xNCkpIChpbnQgLTEzKSkpKSAoaW50IDE4KSkjMTU0	pieces=type::(int-type);;term::(app (app (global int_div) (app (app (global int_add) (app (global int_neg) (int 8))) (app (app (global int_mul) (int -14)) (int -13)))) (int 18))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGludC10eXBlKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X3JlbSkgKGludCA3KSkgKGludCA4KSkjMTU1	pieces=type::(int-type);;term::(app (app (global int_rem) (int 7)) (int 8))
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3xjdHgwKGRhdGEgVmVjICgpICgodmFyIDApKSl8Y3R4MShkYXRhIE5hdCAoKSAoKSl8dHlwZShpbnQtdHlwZSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgVmVjICgpICgodmFyIDApKSkgKGludC10eXBlKSkpIChicmFuY2ggdm5pbCAwIChpbnQgMCkpIChicmFuY2ggdmNvbnMgMyAoaW50IDUpKSkjMTU2	pieces=ctx0::(data Vec () ((var 0)));;ctx1::(data Nat () ());;type::(int-type);;term::(case (var 0) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (int-type))) (branch vnil 0 (int 0)) (branch vcons 3 (int 5)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2VxKSAoZmxvYXQgMi4yNSkpIChmbG9hdCAwLjc1KSkjMTU3	pieces=type::(data Bool () ());;term::(app (app (global float_eq) (float 2.25)) (float 0.75))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgTmF0ICgpICgpKXx0ZXJtKGNhc2UgKG5hdCA0KSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGRhdGEgTmF0ICgpICgpKSkgKGJyYW5jaCBaIDAgKGN0b3IgWikpIChicmFuY2ggUyAxICh2YXIgMCkpKSMxNTg=	pieces=type::(data Nat () ());;term::(case (nat 4) (lam (data Nat () ()) (data Nat () ())) (branch Z 0 (ctor Z)) (branch S 1 (var 0)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgZmxvYXRfZ3QpIChhcHAgKGFwcCAoZ2xvYmFsIGZsb2F0X2RpdikgKGZsb2F0IC0yLjUpKSAoZmxvYXQgMC4yNSkpKSAoZmxvYXQgLTAuNzUpKSMxNTk=	pieces=type::(data Bool () ());;term::(app (app (global float_gt) (app (app (global float_div) (float -2.5)) (float 0.25))) (float -0.75))
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3xjdHgwKGRhdGEgVmVjICgpICgodmFyIDApKSl8Y3R4MShkYXRhIE5hdCAoKSAoKSl8dHlwZSh0eXBlIDApfHRlcm0oY2FzZSAodmFyIDApIChsYW0gKGRhdGEgTmF0ICgpICgpKSAobGFtIChkYXRhIFZlYyAoKSAoKHZhciAwKSkpICh0eXBlIDApKSkgKGJyYW5jaCB2bmlsIDAgKGZsb2F0LXR5cGUpKSAoYnJhbmNoIHZjb25zIDMgKGRhdGEgQmQgKCkgKCkpKSkjMTYw	pieces=ctx0::(data Vec () ((var 0)));;ctx1::(data Nat () ());;type::(type 0);;term::(case (var 0) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (type 0))) (branch vnil 0 (float-type)) (branch vcons 3 (data Bd () ())))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoaW50LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBpbnRfcmVtKSAoaW50IDEwKSkgKGludCAwKSkjMTYx	pieces=type::(int-type);;term::(app (app (global int_rem) (int 10)) (int 0))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9nZSkgKGludCAtMTIpKSAoaW50IDIpKSMxNjI=	pieces=type::(data Bool () ());;term::(app (app (global int_ge) (int -12)) (int 2))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBUZ2YgKCkgKChmbG9hdCAxLjUpKSl8dHlwZShkYXRhIE5hdCAoKSAoKSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSAoZmxvYXQtdHlwZSkgKGxhbSAoZGF0YSBUZ2YgKCkgKCh2YXIgMCkpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKGJyYW5jaCB0Z2YwIDAgKGN0b3IgUyAoY3RvciBaKSkpIChicmFuY2ggdGdmMSAwIChjdG9yIFopKSkjMTYz	pieces=ctx0::(data Tgf () ((float 1.5)));;type::(data Nat () ());;term::(case (var 0) (lam (float-type) (lam (data Tgf () ((var 0))) (data Nat () ()))) (branch tgf0 0 (ctor S (ctor Z))) (branch tgf1 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/subject_reduction	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9zdWJqZWN0X3JlZHVjdGlvbnx0eXBlKGRhdGEgQm9vbCAoKSAoKSl8dGVybShhcHAgKGFwcCAoZ2xvYmFsIGludF9sdCkgKGFwcCAoYXBwIChnbG9iYWwgaW50X3N1YikgKGFwcCAoZ2xvYmFsIGludF9uZWcpIChpbnQgLTExKSkpIChpbnQgMTIpKSkgKGludCAxMCkpIzE2NA==	pieces=type::(data Bool () ());;term::(app (app (global int_lt) (app (app (global int_sub) (app (global int_neg) (int -11))) (int 12))) (int 10))
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3xjdHgwKGRhdGEgVmVjICgpICgodmFyIDApKSl8Y3R4MShkYXRhIE5hdCAoKSAoKSl8dHlwZShmbG9hdC10eXBlKXx0ZXJtKGNhc2UgKHZhciAwKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBWZWMgKCkgKCh2YXIgMCkpKSAoZmxvYXQtdHlwZSkpKSAoYnJhbmNoIHZuaWwgMCAoZmxvYXQgLTQuMCkpIChicmFuY2ggdmNvbnMgMyAoZmxvYXQgLTQuNSkpKSMxNjU=	pieces=ctx0::(data Vec () ((var 0)));;ctx1::(data Nat () ());;type::(float-type);;term::(case (var 0) (lam (data Nat () ()) (lam (data Vec () ((var 0))) (float-type))) (branch vnil 0 (float -4.0)) (branch vcons 3 (float -4.5)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQJtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBUeSAoKSAoKHZhciAwKSkpfGN0eDEodHlwZSAwKXx0eXBlKGRhdGEgTmF0ICgpICgpKXx0ZXJtKGNhc2UgKHZhciAwKSAobGFtICh0eXBlIDApIChsYW0gKGRhdGEgVHkgKCkgKCh2YXIgMCkpKSAoZGF0YSBOYXQgKCkgKCkpKSkgKGJyYW5jaCB0bmF0IDAgKGN0b3IgUyAoY3RvciBTIChjdG9yIFMgKGN0b3IgWikpKSkpIChicmFuY2ggdGJkIDAgKGN0b3IgWikpIChicmFuY2ggdGludCAwIChjdG9yIFopKSAoYnJhbmNoIHRmbHQgMCAoY3RvciBaKSkgKGJyYW5jaCB0cGkgMCAoY3RvciBaKSkgKGJyYW5jaCB0c2lnIDAgKGN0b3IgWikpIChicmFuY2ggdHZlYyAwIChjdG9yIFopKSkjMTY2	pieces=ctx0::(data Ty () ((var 0)));;ctx1::(type 0);;type::(data Nat () ());;term::(case (var 0) (lam (type 0) (lam (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor S (ctor S (ctor S (ctor Z))))) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufGN0eDAoZGF0YSBUeSAoKSAoKGRhdGEgVmVjICgoY3RvciBTIChjdG9yIFopKSkgKCkpKSl8dHlwZShkYXRhIE5hdCAoKSAoKSl8dGVybShjYXNlICh2YXIgMCkgKGxhbSAodHlwZSAwKSAobGFtIChkYXRhIFR5ICgpICgodmFyIDApKSkgKGRhdGEgTmF0ICgpICgpKSkpIChicmFuY2ggdG5hdCAwIChjdG9yIFopKSAoYnJhbmNoIHRiZCAwIChjdG9yIFopKSAoYnJhbmNoIHRpbnQgMCAoY3RvciBaKSkgKGJyYW5jaCB0Zmx0IDAgKGN0b3IgWikpIChicmFuY2ggdHBpIDAgKGN0b3IgWikpIChicmFuY2ggdHNpZyAwIChjdG9yIFopKSAoYnJhbmNoIHR2ZWMgMCAoY3RvciBaKSkpIzE2Nw==	pieces=ctx0::(data Ty () ((data Vec ((ctor S (ctor Z))) ())));;type::(data Nat () ());;term::(case (var 0) (lam (type 0) (lam (data Ty () ((var 0))) (data Nat () ()))) (branch tnat 0 (ctor Z)) (branch tbd 0 (ctor Z)) (branch tint 0 (ctor Z)) (branch tflt 0 (ctor Z)) (branch tpi 0 (ctor Z)) (branch tsig 0 (ctor Z)) (branch tvec 0 (ctor Z)))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoaW50LXR5cGUpfHRlcm0oYXBwIChhcHAgKGdsb2JhbCBpbnRfZGl2KSAoaW50IC0xMikpIChpbnQgMCkpIzE2OA==	pieces=type::(int-type);;term::(app (app (global int_div) (int -12)) (int 0))
antigen-record	kind=typed_term	assay=term/normalization	label=well_typed	seed=-	note=primitive arithmetic (builtin-op global spines)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQBtAAAAA3NpZ20AAAACdjE=	key=dGVybS9ub3JtYWxpemF0aW9ufHR5cGUoZGF0YSBCb29sICgpICgpKXx0ZXJtKGFwcCAoYXBwIChnbG9iYWwgaW50X2xlKSAoaW50IDE3KSkgKGludCAtMTUpKSMxNjk=	pieces=type::(data Bool () ());;term::(app (app (global int_le) (int 17)) (int -15))
antigen-record	kind=typed_term	assay=term/infer_check	label=well_typed	seed=-	note=dependent match (indexed Vec case)	scaffold=g3QAAAACbQAAAAdjdHhfbGVuYQFtAAAAA3NpZ20AAAACdjE=	key=dGVybS9pbmZlcl9jaGVja3xjdHgwKGRhdGEgU3EgKCkgKChuYXQgNCkgKGN0b3IgUyAoY3RvciBaKSkpKXx0eXBlKGRhdGEgTmF0ICgpICgpKXx0ZXJtKGNhc2UgKHZhciAwKSAobGFtIChkYXRhIE5hdCAoKSAoKSkgKGxhbSAoZGF0YSBOYXQgKCkgKCkpIChsYW0gKGRhdGEgU3EgKCkgKCh2YXIgMikgKHZhciAxKSkpIChkYXRhIE5hdCAoKSAoKSkpKSkgKGJyYW5jaCBta3NxIDEgKGN0b3IgUyAoY3RvciBaKSkpKSMxNzA=	pieces=ctx0::(data Sq () ((nat 4) (ctor S (ctor Z))));;type::(data Nat () ());;term::(case (var 0) (lam (data Nat () ()) (lam (data Nat () ()) (lam (data Sq () ((var 2) (var 1))) (data Nat () ())))) (branch mksq 1 (ctor S (ctor Z))))
